/**
 * G1-31 (new in phase 6; docs/guardrails.md section 7 at 1.12; T).
 * Situation: a Metrics chart whose series no formula of the catalogue declares (the production catalogue), or whose
 * formula did not run.
 * Expected: one "Not available yet" line naming the total's missing items and the series' method; no point, bar, total,
 * zero or dash is drawn.
 * Follows from rule 1, "A value exists only if it comes from ... a permitted calculation" and "No numeric stand-in ...
 * charts"; rule 7, "'Not available yet' never appears alone. It names what is missing and offers the action"; G1-28 for
 * an output with no body.
 *
 * View half (this file; phase 6's view-model builder): every series of the four snapshot-reading Metrics pages built
 * over a stored version generated with the production catalogue (no production formula declares a series: the engine's
 * `PRODUCTION_CATALOGUE.series` is empty) reads its one line and nothing else; a breakdown's line names what its total
 * waited for, as the stored proposal names it (the SOVITECH datasets, and the owner's Add where an input is missing),
 * then "SOVITECH's method for <what the series measures>"; a series with no engine total names what its figure waits
 * for (the payback's items, the savings', the lifecycle's). With the TEST catalogue (test runner only): a series the
 * catalogue declares whose formula left no row in the snapshot (generated before it was declared), and one generated by
 * an earlier version of its formula that output only the total (phase 6 part B, A-2: the series did not run there; the
 * page is never refused), read the same way, with no point. The rendered half (the page draws the line in the chart's
 * place, no mark, axis or "0") is the web builder's, in the Metrics pages' component tests titled "G1-31".
 *
 * Beside the case (phase 6 part B): a declared series that ran with every point a gap (its method exists, so it is not
 * named) reads one line naming what its points and its total waited for (rule 7; moved out of G1-31's own tests, whose
 * Expected names the method: V-5); and a series named by no label is refused, never named by its internal key (V-6).
 * Every value is TEST data.
 */
import { describe, expect, test } from 'vitest';
import { SeriesSchema, servedDisplayOf, type DisplayObject, type Series } from '@sovitech/view-model/browser';
import { MetricsNotBuilt, capexView, financialOverviewView, lifecycleView, paybackView, seriesView } from '@sovitech/view-model/server';
import { metricsProposalInput } from './_support/metrics';
import { displayById, PROJECT_ID, SNAPSHOT_ID, testProposalInput } from './_support/proposal';

const DATASETS = 'SOVITECH point templates; SOVITECH cost ranges and benchmarks';

/** The one line of a series that is not available, and the checks every such series passes. */
function lineOf(series: Series, displays: readonly DisplayObject[]): DisplayObject {
  const parsed = SeriesSchema.parse(series);
  expect(parsed.state, series.series).toBe('not_available_yet');
  expect(parsed.points, series.series).toEqual([]);
  expect(parsed.total, series.series).toBeNull();
  expect(parsed.zero, series.series).toBeNull();
  expect(parsed.source, series.series).toBeNull();
  expect(parsed.notAvailable, series.series).toBe(`proposal:${SNAPSHOT_ID}.series.${series.series}.notAvailable`);
  const line = displayById(displays, parsed.notAvailable ?? '');
  expect(line.kind).toBe('line');
  expect(line.shape).toBe('missing');
  expect(line.missing).toBe('not_available_yet');
  // Never a zero or a dash in its place (rule 1, rule 7).
  for (const text of [servedDisplayOf(line).text, ...(servedDisplayOf(line).lines ?? [])]) expect(text).not.toMatch(/^\s*(0|-|–|—)\s*$/u);
  // Nothing of the series is served besides its line.
  expect(displays.filter((display) => display.valueId.startsWith(`proposal:${SNAPSHOT_ID}.series.${series.series}.`)).map((display) => display.valueId)).toEqual([parsed.notAvailable]);
  return line;
}

describe('G1-31 · rule 1 · rule 7: a Metrics chart no formula declares, or whose formula did not run, reads one "Not available yet" line naming what is missing', () => {
  test('G1-31 · R-088 · R-091 · R-094 · R-103: Financial Overview\'s breakdowns name their total\'s datasets and their method; its cash flow names the payback\'s items and its method', () => {
    const built = financialOverviewView({ projectId: PROJECT_ID, header: testProposalInput().header, proposal: testProposalInput() });
    if (built.view.state !== 'generated') throw new Error('a stored version is read');
    // The total's own line, as the stored proposal names what it waited for: the datasets, then the owner inputs missing.
    const total = displayById(built.displayObjects, `proposal:${SNAPSHOT_ID}.outputs.capex.preliminaryEstimate`).text;
    expect(total.startsWith(`Not available yet: ${DATASETS}`)).toBe(true);
    const bySystem = lineOf(built.view.costBreakdown.bySystem, built.displayObjects);
    expect(bySystem.text).toBe(`${total}; SOVITECH's method for investment by system`);
    const byLevel = lineOf(built.view.costBreakdown.byBuildingArea, built.displayObjects);
    expect(byLevel.text).toBe(`${total}; SOVITECH's method for investment by level`);
    const cashFlow = lineOf(built.view.annualCashFlow, built.displayObjects);
    expect(cashFlow.text).toBe("Not available yet: the duration unit and the financial method for the payback; SOVITECH's method for annual cash flow");
  });

  test('G1-31 · R-089 · R-096 · R-097: CAPEX, Payback and Lifecycle draw no chart; each line names what it waits for and its method', () => {
    const input = testProposalInput();
    const page = { projectId: PROJECT_ID, header: input.header, proposal: input };
    const capex = capexView(page);
    const payback = paybackView(page);
    const lifecycle = lifecycleView(page);
    if (capex.view.state !== 'generated' || payback.view.state !== 'generated' || lifecycle.view.state !== 'generated') throw new Error('a stored version is read');
    const total = displayById(capex.displayObjects, `proposal:${SNAPSHOT_ID}.outputs.capex.preliminaryEstimate`).text;
    expect(total.startsWith(`Not available yet: ${DATASETS}`)).toBe(true);
    expect(lineOf(capex.view.bySystem, capex.displayObjects).text).toBe(`${total}; SOVITECH's method for investment by system`);
    expect(lineOf(payback.view.savingsBreakdown, payback.displayObjects).text).toBe(
      "Not available yet: the energy-price unit; SOVITECH savings factors; the open question on annual amounts; SOVITECH's method for savings by stream",
    );
    expect(lineOf(payback.view.cumulativeCashFlow, payback.displayObjects).text).toBe(
      "Not available yet: the duration unit and the financial method for the payback; SOVITECH's method for cumulative cash flow",
    );
    const lifecycleItems = 'the duration unit; service lives from a datasheet, an engineer or an approved dataset; the lifecycle cost method';
    expect(lineOf(lifecycle.view.costComparison, lifecycle.displayObjects).text).toBe(`Not available yet: ${lifecycleItems}; SOVITECH's method for lifecycle cost comparison`);
    expect(lineOf(lifecycle.view.costBreakdown, lifecycle.displayObjects).text).toBe(`Not available yet: ${lifecycleItems}; SOVITECH's method for lifecycle cost breakdown`);
    expect(lineOf(lifecycle.view.bySystem, lifecycle.displayObjects).text).toBe(`Not available yet: ${lifecycleItems}; SOVITECH's method for lifecycle cost by system`);
  });

  test('G1-31 · rule 7: where the total waits for an owner input, the series\' line offers the owner\'s Add, as the stored proposal\'s line does', () => {
    const input = testProposalInput();
    const built = seriesView(input, { key: 'capex.bySystem', kind: 'breakdown', totalOutput: 'capex.preliminaryEstimate', beside: {} });
    const line = lineOf(built.series, built.displayObjects);
    const total = input.snapshot.outputs.find((row) => row.output === 'capex.preliminaryEstimate');
    expect(total?.candidateId).toBeNull();
    // The owner inputs the stored proposal's own line names, each with its Add (rule 7; G7-21).
    const proposalLine = displayById(capexView({ projectId: PROJECT_ID, header: input.header, proposal: input }).displayObjects, `proposal:${SNAPSHOT_ID}.outputs.capex.preliminaryEstimate`);
    expect(line.actions).toEqual(proposalLine.actions);
    expect((line.actions ?? []).length).toBeGreaterThan(0);
  });

  test('G1-31 (TEST catalogue) · a declared series whose formula left no row in the snapshot draws nothing; its line names what it waits for and its method', () => {
    // Generated before the series was declared: the snapshot holds none of its rows.
    const { input } = metricsProposalInput({ buildingType: 'hotel', scope: { hvac: 'include', lighting: 'include' } });
    const older = { ...input, snapshot: { ...input.snapshot, outputs: input.snapshot.outputs.filter((row) => row.formulaId !== 'TEST-capexBySystem') } };
    const none = seriesView(older, { key: 'capex.TEST_bySystem', kind: 'breakdown', totalOutput: 'capex.TEST_bySystem.total', waitsFor: 'TEST investment by system', label: 'TEST cost by system', beside: {} });
    expect(lineOf(none.series, none.displayObjects).text).toBe("Not available yet: TEST investment by system; SOVITECH's method for test cost by system");
  });

  test('G1-31 · A-2 (phase 6 part B): a version generated by an earlier formula version that output the total and no line reads the series\' one line naming its method; the page is not refused', () => {
    // P-6-SERIES-SIGNATURES: a next version outputs lines beside a total every earlier version already stored.
    const { input } = metricsProposalInput({ buildingType: 'hotel', scope: { hvac: 'include', lighting: 'include' } });
    const total = input.snapshot.outputs.find((row) => row.output === 'capex.TEST_bySystem.total');
    expect(total?.candidateId).not.toBeNull();
    const earlier = { ...input, snapshot: { ...input.snapshot, outputs: input.snapshot.outputs.filter((row) => row.formulaId !== 'TEST-capexBySystem' || row.output === 'capex.TEST_bySystem.total') } };
    const built = seriesView(earlier, { key: 'capex.TEST_bySystem', kind: 'breakdown', totalOutput: 'capex.TEST_bySystem.total', label: 'TEST cost by system', beside: {} });
    expect(lineOf(built.series, built.displayObjects).text).toBe("Not available yet: SOVITECH's method for test cost by system");
  });
});

describe('G1-31 (beside the case) · phase 6 part B', () => {
  test('(beside the case) · rule 7 · V-5: a declared series that ran with every point a gap reads one line naming what its points and its total waited for (its method exists, so it is not named), and draws nothing', () => {
    // Every point a gap (no building type: every line ranges over a type with no TEST range): no axis, one line naming the input.
    const { input: unknownType } = metricsProposalInput({ scope: { hvac: 'include', lighting: 'include' } });
    const gaps = seriesView(unknownType, { key: 'capex.TEST_bySystem', kind: 'breakdown', totalOutput: 'capex.TEST_bySystem.total', label: 'TEST cost by system', beside: {} });
    const line = lineOf(gaps.series, gaps.displayObjects);
    expect(line.text).toBe('Not available yet: building type');
    expect(line.actions?.map((action) => action.kind)).toEqual(['add']);
  });

  test('(beside the case) · rule 7 · rule 8 · V-6: a series named by no label is refused, never named by its internal key', () => {
    const input = testProposalInput();
    expect(() => seriesView(input, { key: 'capex.unlabelled', kind: 'breakdown', totalOutput: 'capex.preliminaryEstimate', beside: {} })).toThrow(MetricsNotBuilt);
    const { input: test } = metricsProposalInput({ buildingType: 'hotel', scope: { hvac: 'include' } });
    expect(() => seriesView(test, { key: 'capex.TEST_bySystem', kind: 'breakdown', totalOutput: 'capex.TEST_bySystem.total', beside: {} })).toThrow(MetricsNotBuilt);
  });
});
