/**
 * G7-19 (new in phase 5, for the integrator to index; rule 7, "Still reading 2 files. Your estimate will update when
 * they finish."; 2.4, "A generated proposal keeps a snapshot"; PRD R-110, US-PROPOSAL-11 AC6).
 * Situation: the documents still being read at Generate finish.
 * Expected: a new version is stored, and the first keeps its snapshot.
 *
 * Through the API over a TEST database and the analysis worker with a scripted extractor (the sandbox stand-in of
 * ./_support/api.ts) and the worker's job-ended step as worker-main wires it (apps/api/src/proposal/service.ts
 * `regenerateAfterAnalysis`): a fixture uploaded, Generate while it is queued (the first version records it as pending),
 * then the worker reads it: a second version is generated by the system, recording nothing pending; the first keeps
 * its snapshot (its rows, candidate ids and inputs hash unchanged) and stays readable; running the step again stores
 * nothing more (nothing regenerates silently beyond rule 7's promise). Every account is TEST data; the file is a fixture.
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { assertGatesStartupSafe } from '@sovitech/registry/gates';
import { GenerateResponseSchema, ProposalResponseSchema, ProposalVersionsResponseSchema } from '@sovitech/view-model/browser';
import { AnalysisWorker } from '../../apps/api/src/jobs/worker';
import { regenerateAfterAnalysis } from '../../apps/api/src/proposal/service';
import { ScriptedRunner, fixtureBytes, signIn, startTestApi, upload, type Auth, type TestApi } from './_support/api';
import { pdfOutput } from './_support/outputs';
import { newOwnerProject } from './_support/workspace-store';

let api: TestApi;
let owner: Auth;

beforeAll(async () => {
  api = await startTestApi({ devLogin: true });
  const [ownerId] = api.devAccountIds;
  if (ownerId === undefined) throw new Error('no TEST development owner');
  owner = await signIn(api, ownerId);
}, 180_000);

afterAll(async () => {
  await api.stop();
});

async function snapshotRows(snapshotId: string): Promise<unknown> {
  return {
    snapshot: await api.database.asAdministrator('SELECT inputs_hash, created_by FROM sovitech.proposal_snapshots WHERE id = $1', [snapshotId]),
    candidates: await api.database.asAdministrator('SELECT candidate_id FROM sovitech.proposal_snapshot_candidates WHERE snapshot_id = $1 ORDER BY candidate_id', [snapshotId]),
    outputs: await api.database.asAdministrator('SELECT output_key, candidate_id, missing FROM sovitech.proposal_snapshot_outputs WHERE snapshot_id = $1 ORDER BY ordinal', [snapshotId]),
    pending: await api.database.asAdministrator('SELECT document_id FROM sovitech.proposal_snapshot_pending_documents WHERE snapshot_id = $1', [snapshotId]),
  };
}

describe('G7-19 · rule 7: the documents still being read at Generate finish', { timeout: 90_000 }, () => {
  it('G7-19 · US-PROPOSAL-11 AC6 · R-110: a new version is stored by the system, and the first keeps its snapshot', async () => {
    const { projectId } = await newOwnerProject(api, owner, 'G7-19');
    expect((await upload(api, owner, projectId, 'memoriu-tehnic.pdf', fixtureBytes('fixtures/pdf/memoriu-tehnic.pdf'))).status).toBe(201);
    const generated = await api.app.inject({ method: 'POST', url: `/api/projects/${projectId}/proposals`, headers: { ...owner }, payload: {} });
    expect(generated.statusCode, generated.body).toBe(201);
    const { snapshotId: first } = GenerateResponseSchema.parse(generated.json());
    const firstRows = await snapshotRows(first);
    expect((firstRows as { pending: unknown[] }).pending).toHaveLength(1);

    const gates = assertGatesStartupSafe();
    const regenerated: (string | null)[] = [];
    const worker = new AnalysisWorker({ store: api.services.store, files: api.files, log: api.services.log }, new ScriptedRunner((_job, job) => pdfOutput(job, 'fixtures/pdf/ground-truth/memoriu-tehnic.json')), {
      workerId: 'test-worker-g7-19',
      serviceId: api.extractionAccountId,
      gates,
      maxAttempts: 1,
      retryAfterSeconds: 0,
      staleAfterSeconds: 600,
      afterJobEnded: async (job) => {
        regenerated.push(await regenerateAfterAnalysis(api.services, gates, { projectId: job.projectId, systemAccountId: api.extractionAccountId }));
      },
    });
    expect((await worker.drain()).map((step) => step.kind)).toEqual(['done']);
    expect(regenerated).toHaveLength(1);
    const second = regenerated[0];
    expect(typeof second).toBe('string');

    const versions = ProposalVersionsResponseSchema.parse((await api.app.inject({ method: 'GET', url: `/api/projects/${projectId}/proposals`, headers: { ...owner } })).json());
    expect(versions.view.versions.map((version) => version.snapshotId)).toEqual([second, first]);
    const [secondSnapshot] = await api.database.asAdministrator<{ created_by: string }>('SELECT created_by FROM sovitech.proposal_snapshots WHERE id = $1', [second]);
    expect(secondSnapshot?.created_by).toBe(api.extractionAccountId);
    expect(await api.database.asAdministrator('SELECT document_id FROM sovitech.proposal_snapshot_pending_documents WHERE snapshot_id = $1', [second])).toEqual([]);
    expect(await snapshotRows(first)).toEqual(firstRows);
    const older = ProposalResponseSchema.parse((await api.app.inject({ method: 'GET', url: `/api/projects/${projectId}/proposals/${first}`, headers: { ...owner } })).json());
    expect(older.view.latest).toBe(false);
    // Nothing more regenerates: the latest version recorded nothing pending.
    expect(await regenerateAfterAnalysis(api.services, gates, { projectId, systemAccountId: api.extractionAccountId })).toBeNull();
  });
});
