/**
 * Emits the zod side of the contract from the loaded schema: src/generated/zod.ts
 * (one strict schema and one type per def) and src/generated/annotations.ts (the
 * contract version, the entry points, the invariant ids and the rule tables the
 * invariants read). Every object is `z.strictObject`, so an unknown key is refused.
 */
import { isFixedTuple, tupleLength, type ContractSchema, type Def, type JsonValue, type Node } from './subset';

export const GENERATED_HEADER = [
  '// GENERATED by packages/extraction-contract/src/generator from',
  '// packages/extraction-contract/src/extraction-contract.schema.json. Do not edit: change the',
  '// schema and run `pnpm --filter @sovitech/extraction-contract generate`. A drift test fails',
  '// when this file and the schema disagree.',
].join('\n');

const INDENT = '  ';

function literal(value: string): string {
  return JSON.stringify(value);
}

function chain(base: string, calls: readonly (string | undefined)[]): string {
  return calls.reduce<string>((expression, call) => (call === undefined ? expression : `${expression}.${call}`), base);
}

function bound(method: 'min' | 'max', value: number | undefined): string | undefined {
  return value === undefined ? undefined : `${method}(${String(value)})`;
}

function expression(node: Node, depth: number): string {
  switch (node.kind) {
    case 'ref':
      return `${node.target}Schema`;
    case 'object': {
      if (node.properties.length === 0) return 'z.strictObject({})';
      const inner = INDENT.repeat(depth + 1);
      const lines = node.properties.map((property) => {
        const value = expression(property.node, depth + 1);
        return `${inner}${property.key}: ${property.required ? value : `${value}.optional()`},`;
      });
      return `z.strictObject({\n${lines.join('\n')}\n${INDENT.repeat(depth)}})`;
    }
    case 'array': {
      if (isFixedTuple(node)) return `z.tuple([${Array.from({ length: tupleLength(node) }, () => expression(node.items, depth)).join(', ')}])`;
      const array = chain(`z.array(${expression(node.items, depth)})`, [bound('min', node.minItems), bound('max', node.maxItems)]);
      return node.uniqueItems ? `unique(${array})` : array;
    }
    case 'string': {
      if (node.enumValues !== undefined) return `z.enum([${node.enumValues.map(literal).join(', ')}])`;
      if (node.constValue !== undefined) return `z.literal(${literal(node.constValue)})`;
      const options = [
        node.pattern === undefined ? undefined : `pattern: ${literal(node.pattern)}`,
        node.minLength === undefined ? undefined : `minLength: ${String(node.minLength)}`,
        node.maxLength === undefined ? undefined : `maxLength: ${String(node.maxLength)}`,
      ].filter((option): option is string => option !== undefined);
      return options.length === 0 ? 'z.string()' : `text({ ${options.join(', ')} })`;
    }
    case 'integer':
      if (node.enumValues !== undefined) return `z.union([${node.enumValues.map((value) => `z.literal(${String(value)})`).join(', ')}])`;
      return chain('z.int()', [bound('min', node.minimum), bound('max', node.maximum)]);
    case 'number':
      return chain('z.number()', [bound('min', node.minimum), bound('max', node.maximum)]);
    case 'boolean':
      return 'z.boolean()';
    case 'oneOf': {
      const branches = node.branches.map((branch) => `${branch}Schema`).join(', ');
      return node.discriminator === undefined
        ? `z.union([${branches}])`
        : `z.discriminatedUnion(${literal(node.discriminator)}, [${branches}])`;
    }
  }
}

function defBlock(def: Def): string {
  const base = expression(def.node, 0);
  const value = def.invariants.length === 0 ? base : `withInvariants(${base}, [${def.invariants.map(literal).join(', ')}])`;
  return [`export const ${def.name}Schema = ${value};`, `export type ${def.name} = z.infer<typeof ${def.name}Schema>;`].join('\n');
}

function constant(name: string, value: JsonValue): string {
  return `export const ${name} = ${JSON.stringify(value, null, 2)} as const;`;
}

/** src/generated/zod.ts */
export function emitZod(schema: ContractSchema): string {
  const usesText = schema.defs.some((def) => JSON.stringify(def.node).includes('"kind":"string"'));
  const helpers = ['unique', 'withInvariants', ...(usesText ? ['text'] : [])].sort();
  return [
    GENERATED_HEADER,
    `import { z } from 'zod';`,
    `import { ${helpers.join(', ')} } from '../runtime';`,
    '',
    ...schema.defs.map((def) => `${defBlock(def)}\n`),
  ].join('\n');
}

/** src/generated/annotations.ts: constants only, no imports, so the invariants can read them without a cycle. */
export function emitAnnotations(schema: ContractSchema): string {
  return [
    GENERATED_HEADER,
    '',
    constant('CONTRACT_VERSION', schema.version),
    '',
    constant('ENTRY_POINTS', schema.entryPoints),
    '',
    '/** Every `x-invariants` id in the schema: src/invariants.ts and the Python _invariants.py implement exactly these. */',
    constant('INVARIANT_IDS', schema.invariantIds),
    '',
    '/** ExtractionOutput `x-format-rules`: per format, the statuses, the G12-1 word, the sections, the finding locators and the derivatives it may carry. */',
    constant('FORMAT_RULES', schema.formatRules),
    '',
    '/** IfcProposalMechanism `x-mechanism-rules`: the gates each mechanism waits for at least, and whether it needs a dataset. */',
    constant('MECHANISM_RULES', schema.mechanismRules),
    '',
    '/** EvidenceLocator `x-ifc-locator-keys`: keys that would carry an IFC locator, refused with the code ifc_field (G1-13). */',
    constant('IFC_LOCATOR_KEYS', schema.ifcLocatorKeys),
    '',
  ].join('\n');
}
