/**
 * Emits the Python side of the contract: _generated.py (a type alias for every
 * scalar, enum and union def, and a frozen dataclass for every object def) in
 * the extractor's contract package. The Python validator reads the constraints
 * from schema.json, a byte copy of the source that generate.ts writes beside it,
 * so the dataclasses carry types only and the one schema carries every rule.
 *
 * The output is laid out the way `ruff format` lays it out (line length 100, the
 * extractor's pyproject.toml), so `pnpm test:py` passes on a fresh generation;
 * the drift test and `ruff format --check` both guard it.
 */
import { isFixedTuple, tupleLength, snakeCase, type ContractSchema, type Def, type Node } from './subset';

const LINE_LENGTH = 100;
const INDENT = '    ';

export const PYTHON_HEADER = [
  '"""Generated by packages/extraction-contract/src/generator: do not edit.',
  '',
  'Source: packages/extraction-contract/src/extraction-contract.schema.json. Change the schema and',
  'run `pnpm --filter @sovitech/extraction-contract generate`; a drift test fails when this file,',
  'schema.json and the source disagree. The types are here; every constraint is in schema.json,',
  'which _validate.py reads, so the Python side and the zod side check the same rules.',
  '"""',
].join('\n');

function quote(value: string): string {
  return JSON.stringify(value);
}

function pascal(key: string): string {
  return `${key.charAt(0).toUpperCase()}${key.slice(1)}`;
}

/** `name = (items)` on one line when it fits, else one item per line with a trailing comma. */
function sequence(prefix: string, open: string, close: string, items: readonly string[], indent: string): string {
  const single = `${indent}${prefix}${open}${items.join(', ')}${close}`;
  if (single.length <= LINE_LENGTH) return single;
  return [`${indent}${prefix}${open}`, ...items.map((item) => `${indent}${INDENT}${item},`), `${indent}${close}`].join('\n');
}

/**
 * `type Name = A | B` on one line when it fits; else in parentheses, on one
 * indented line when that fits, else one member per line.
 */
function unionAlias(name: string, members: readonly string[]): string {
  const chain = members.join(' | ');
  const single = `type ${name} = ${chain}`;
  if (single.length <= LINE_LENGTH) return single;
  if (`${INDENT}${chain}`.length <= LINE_LENGTH) return [`type ${name} = (`, `${INDENT}${chain}`, ')'].join('\n');
  return [`type ${name} = (`, `${INDENT}${members[0] ?? ''}`, ...members.slice(1).map((member) => `${INDENT}| ${member}`), ')'].join('\n');
}

interface Emitted {
  readonly aliases: string[];
  readonly classes: string[];
  /** Every top-level Python name emitted so far, classes included. */
  readonly names: Set<string>;
}

function claim(name: string, out: Emitted): void {
  if (out.names.has(name)) throw new Error(`python name ${name} is emitted twice`);
  out.names.add(name);
}

function literalAlias(name: string, values: readonly string[], out: Emitted): string {
  claim(name, out);
  out.aliases.push(sequence(`type ${name} = `, 'Literal[', ']', values, ''));
  return name;
}

/** The Python type of a node. Inline enums become named aliases (hint), so no field line runs long. */
function pyType(node: Node, hint: string, out: Emitted): string {
  switch (node.kind) {
    case 'ref':
      return node.target;
    case 'array': {
      const item = pyType(node.items, `${hint}Item`, out);
      return isFixedTuple(node) ? `tuple[${Array.from({ length: tupleLength(node) }, () => item).join(', ')}]` : `tuple[${item}, ...]`;
    }
    case 'string':
      if (node.constValue !== undefined) return `Literal[${quote(node.constValue)}]`;
      if (node.enumValues !== undefined) return literalAlias(hint, node.enumValues.map(quote), out);
      return 'str';
    case 'integer':
      if (node.enumValues !== undefined) return literalAlias(hint, node.enumValues.map(String), out);
      return 'int';
    case 'number':
      return 'float';
    case 'boolean':
      return 'bool';
    case 'object':
    case 'oneOf':
      throw new Error(`${hint}: an inline ${node.kind} is not supported; make it a def`);
  }
}

function emitDef(def: Def, out: Emitted): void {
  const node = def.node;
  if (node.kind === 'object') {
    const required = node.properties.filter((property) => property.required);
    const optional = node.properties.filter((property) => !property.required);
    const fields = [
      ...required.map((property) => `${INDENT}${snakeCase(property.key)}: ${pyType(property.node, `${def.name}${pascal(property.key)}`, out)}`),
      ...optional.map(
        (property) => `${INDENT}${snakeCase(property.key)}: ${pyType(property.node, `${def.name}${pascal(property.key)}`, out)} | None = None`,
      ),
    ];
    for (const field of fields) if (field.length > LINE_LENGTH) throw new Error(`python field line too long: ${field}`);
    out.classes.push(
      ['@dataclass(frozen=True, slots=True)', `class ${def.name}:`, `${INDENT}"""#/$defs/${def.name}"""`, '', ...fields].join('\n'),
    );
    return;
  }
  if (node.kind === 'oneOf') {
    claim(def.name, out);
    out.aliases.push(unionAlias(def.name, node.branches));
    return;
  }
  if ((node.kind === 'string' || node.kind === 'integer') && node.enumValues !== undefined) {
    literalAlias(def.name, node.kind === 'string' ? node.enumValues.map(quote) : node.enumValues.map(String), out);
    return;
  }
  const alias = `type ${def.name} = ${pyType(node, `${def.name}Item`, out)}`;
  claim(def.name, out);
  out.aliases.push(alias);
}

/** services/extractor/src/sovitech_extractor/contract/_generated.py */
export function emitPython(schema: ContractSchema): string {
  const out: Emitted = { aliases: [], classes: [], names: new Set() };
  const classNames = schema.defs.filter((def) => def.node.kind === 'object').map((def) => def.name);
  for (const name of classNames) claim(name, out);
  for (const def of schema.defs) emitDef(def, out);
  const constants = [
    `CONTRACT_VERSION = ${quote(schema.version)}`,
    sequence('ENTRY_POINTS = ', '(', ')', schema.entryPoints.map(quote), ''),
    sequence('INVARIANT_IDS = ', '(', ')', schema.invariantIds.map(quote), ''),
  ];
  const body = [
    PYTHON_HEADER,
    '',
    'from __future__ import annotations',
    '',
    'from dataclasses import dataclass',
    'from typing import Literal',
    '',
    ...constants,
    '',
    ...out.aliases,
    '',
    '',
    out.classes.join('\n\n\n'),
    '',
  ];
  return body.join('\n');
}
