/**
 * Reports (DB-18; `/projects/:projectId/reports`; PRD R-119, R-120, R-123 "Until decided"; US-REPORTS-05, US-REPORTS-14
 * AC1; the contract's `reports.list`; docs/adr/0049 decision 5, 0050 decision 3; dashboards 7.1.1-D6, D8, E1 to E3).
 *
 * The register of what was generated for the project: each proposal PDF the owner downloaded from the stored proposal
 * (a generated output, R-119; the proposal itself is not a row of its own: US-REPORTS-05 AC2 is left off, D-02).
 *
 * - **The toolbar** (US-REPORTS-05 AC14's search, category and date sort, bound to the list query: the API filters,
 *   sorts and pages): the kit's one search field ("Search reports...", sent a moment after the last key), "All
 *   Categories", and the sort box "Date (Newest)" / "Date (Oldest)" with its separate direction toggle, as the
 *   approved screen draws them. No "All Statuses" (R-119).
 * - **The register**: Name (the output's name, bound, with "Superseded: inputs changed on <date>" under it where its
 *   snapshot's quotation record went stale: G10-2; none in the live app), Category, Date Generated and Generated By
 *   (bound record values; "Generated By" names who started it and never implies review: 7.1.1-D8; a demo account on
 *   the demo, never a real person: 7.1.1-D6), and per row "Show preview" and a download under one visible "Actions"
 *   heading (DB-18; DR-7). Category and Date Generated keep one line, Name keeps a minimum width, and Generated By
 *   wraps (DR-8). Previous and next only: no page number, no "Showing <a>–<b> of <n> reports" (G2-1; proposal 7.2.30).
 *   No Status column, "⋯" menu or "View" (R-119, R-123).
 * - **The preview** (US-REPORTS-05 AC5, AC9 to AC12): the selected row (the first one until the owner picks another)
 *   with its cover, drawn as the PDF's cover in the PDF's order (DR-10): "Preliminary proposal", the project's name as
 *   stored, bound (never the mockups' hotel: OD-5), and the demo line on the demo project, which nothing replaces
 *   (7.1.1-E1); no photo, tagline, "CONFIDENTIAL", logo or typeset wordmark (OD-2, OD-3, 7.2.9, ADR 0050 decision 7).
 *   Then its details and Download, full width; the cover is capped in width so Download sits in the first screen at
 *   1440x900, above the status footer (DB-18; DR-4). No Pages or File Size (G2-1).
 * - **Download** (US-REPORTS-05 AC6; ADR 0050 decision 3): reads the stored output's file, printed again from its
 *   snapshot, and saves it; one request per press, never disabled (rule 7); a failure says so beside the control that
 *   was pressed (under the preview's Download, or under the toolbar for a row's button, which it then describes; DR-9),
 *   and the button takes presses again.
 * - **Not built** (R-119, R-120, R-123 "Until decided"): "+ Generate Report", the template tiles, "View All Templates →",
 *   "View", the Status column and filter, the row menu, a Compliance Report, any live value, the "BMS Live" footer.
 * - **States:** loading (one polite line), failed (what could not be loaded, Try again), nothing generated yet (what
 *   to do, with "Open the Proposal page", an in-page link like the others: DR-13), nothing matching the search or the
 *   category.
 * The demo line is the frame's footer, and the cover's on the demo (rule 10; GS-1).
 *
 * Undesigned parts (the cover's content, the empty state) per the frontend-design skill within the brand. The cover is
 * drawn as a page and marked `data-paper`, which takes the print scope's light values (tokens.css), as the PDF's pages
 * do; it holds no image of any kind.
 */
import { ArrowDownUp, ArrowRight, ChevronDown, Download, FileText } from 'lucide-react';
import { useEffect, useId, useMemo, useRef, useState, type ReactNode } from 'react';
import { Link } from 'react-router';
import { Button, FieldError, Icon, PageHeader, Pager, RegisterTable, SearchField, StatusLine, Value, ValueName, type RegisterColumn } from '@sovitech/ui';
import { OUTPUT_KINDS, type ReportRow, type ReportsResponse } from '@sovitech/view-model/browser';
import { isSignedOut, request } from '../../../api/client';
import { useLoad } from '../../../api/use-load';
import { copy } from '../../../copy';
import { LoadFailed, Loading } from '../../../pages/PageState';
import { exportFilePath, saveFile } from '../../../proposal/download';
import { useOnSignedOut } from '../../../session/SessionProvider';
import { useRenderReady } from '../../../shell/render-ready';
import { useWizard } from '../../../wizard/WizardProvider';
import { useInFlight } from '../../../wizard/use-in-flight';
import type { Displays } from '../../../wizard/use-step-view';
import { pagePath } from '../../navigation';
import { useKept } from '../equipment/use-kept';

const REP = copy.reports;
const ALL = '';

/** How long the search waits after the last key before it is sent. */
export const REPORTS_SEARCH_DELAY_MS = 300;

type Sort = 'newest' | 'oldest';

interface ReportsQueryState {
  readonly search: string;
  readonly category: string;
  readonly sort: Sort;
  readonly page: number;
}

const START: ReportsQueryState = { search: '', category: ALL, sort: 'newest', page: 1 };

/** The list query as the client sends it: an empty or default value is not sent (the API's defaults). */
export function reportsQuery(state: ReportsQueryState): Record<string, string | undefined> {
  return {
    search: state.search.trim() === '' ? undefined : state.search.trim(),
    category: state.category === ALL ? undefined : state.category,
    sort: state.sort === 'newest' ? undefined : state.sort,
    page: state.page <= 1 ? undefined : String(state.page),
  };
}

/** A compact select of the toolbar (40px, the control boundary), with its name for screen readers. */
function ToolbarSelect({ label, value, options, onChange }: { readonly label: string; readonly value: string; readonly options: ReadonlyArray<{ readonly value: string; readonly label: string }>; readonly onChange: (value: string) => void }) {
  const id = useId();
  return (
    <div className="relative flex h-10 min-w-[200px] items-center rounded-(--sov-radius-surface) border border-(--sov-control-border) transition-colors duration-300 focus-within:outline-2 focus-within:outline-offset-2 focus-within:outline-(--sov-focus-ring) hover:border-(--sov-text-primary)">
      <label htmlFor={id} className="sr-only">
        {label}
      </label>
      <select id={id} value={value} onChange={(event) => onChange(event.currentTarget.value)} className="h-full w-full appearance-none bg-transparent pr-9 pl-3 text-[14px] text-(--sov-text-primary) outline-none">
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
      <span className="pointer-events-none absolute right-3 text-(--sov-text-tertiary)">
        <Icon icon={ChevronDown} size="small" />
      </span>
    </div>
  );
}

/**
 * The cover of the selected output (US-REPORTS-05 AC9 to AC11), as the PDF's cover draws it, in its order (DR-10): the
 * title "Preliminary proposal", the project's name (bound), then the demo line on the demo. A page in miniature, capped
 * at 210px wide (an A4 page's proportions), so the details and Download stay in the first screen (DR-4).
 */
function Cover({ data, displays }: { readonly data: ReportsResponse; readonly displays: Displays }) {
  const name = displays.get(data.project.name);
  return (
    <div
      data-paper=""
      className="mx-auto flex aspect-[1/1.414] w-full max-w-[210px] flex-col justify-between gap-3 rounded-(--sov-radius-surface) border border-(--sov-border-hover) bg-(--sov-bg) p-4 text-(--sov-text-primary)"
      data-report-cover=""
    >
      <div className="flex flex-col gap-2">
        <p className="text-[16px] leading-5 font-light" data-cover-title="">
          {REP.coverTitle}
        </p>
        <p className="sov-text-small text-(--sov-text-primary)" data-cover-project="">
          {name === undefined ? null : <ValueName display={name} showBadge={false} />}
        </p>
      </div>
      {data.project.demoLine === null ? null : (
        <div className="border-t border-(--sov-border) pt-3 [&_.sov-status-line]:text-[12px] [&_.sov-status-line]:leading-4 [&_.sov-status-line]:text-(--sov-text-primary)" data-cover-demo-line="">
          <StatusLine line={data.project.demoLine} />
        </div>
      )}
    </div>
  );
}

/** One detail of the preview: its name (catalogue) and its served value. */
function Detail({ name, children }: { readonly name: string; readonly children: ReactNode }) {
  return (
    <div className="grid grid-cols-[96px_minmax(0,1fr)] items-start gap-3 py-1">
      <dt className="sov-text-caption pt-0.5">{name}</dt>
      <dd className="m-0 min-w-0 text-[14px] [&_.sov-value\_\_text]:text-[14px] [&_.sov-value\_\_text]:leading-5">{children}</dd>
    </div>
  );
}

export function ReportsPage() {
  const { projectId, publishEnvelope } = useWizard();
  const onSignedOut = useOnSignedOut();
  const [query, setQuery] = useState<ReportsQueryState>(START);
  const [text, setText] = useState('');
  const [chosen, setChosen] = useState<string | null>(null);
  const downloading = useInFlight();
  // Where a failed download was pressed (DR-9): its message shows beside that control.
  const [failed, setFailed] = useState<{ readonly from: 'preview' } | { readonly from: 'row'; readonly outputId: string } | null>(null);
  const errorId = useId();
  const previewErrorId = useId();
  const previewAlert = useRef<HTMLDivElement | null>(null);
  const sent = reportsQuery(query);
  const key = JSON.stringify(sent);
  const { state, reload } = useLoad((signal) => request('reports.list', { params: { projectId }, query: sent, signal }), [projectId, key]);
  // The rows on screen stay while a new query is answered (`aria-busy` on the table): the one kept-view helper.
  const { data, displays } = useKept(state.data);
  useEffect(() => {
    if (state.status !== 'loading' && state.data !== undefined) publishEnvelope(state.data);
  }, [state, publishEnvelope]);
  useRenderReady(state.status !== 'loading');

  // A failure under the preview's Download is brought clear of the status footer once, when it appears (DR-4, DR-9).
  useEffect(() => {
    if (failed?.from === 'preview') previewAlert.current?.scrollIntoView?.({ block: 'nearest' });
  }, [failed]);

  // A focus the page moves itself (WCAG 2.4.3): the page's main region when it opens.
  useEffect(() => {
    document.getElementById('main')?.focus({ preventScroll: true });
  }, []);

  // The search is sent a moment after the last key, never on every key; a new search starts at the first page.
  useEffect(() => {
    if (text === query.search) return;
    const timer = window.setTimeout(() => setQuery((previous) => ({ ...previous, search: text, page: 1 })), REPORTS_SEARCH_DELAY_MS);
    return () => window.clearTimeout(timer);
  }, [text, query.search]);

  const rows = useMemo(() => data?.view.rows ?? [], [data]);
  // The preview shows the chosen row while the list holds it, else the first row (as the approved screen does).
  const selected = rows.find((row) => row.outputId === chosen) ?? rows[0];
  const loading = state.status === 'loading';

  const download = (row: ReportRow, from: 'preview' | 'row') => {
    void downloading.run(async () => {
      setFailed(null);
      try {
        await saveFile(exportFilePath(projectId, row.outputId));
      } catch (error) {
        if (isSignedOut(error)) {
          onSignedOut();
          return;
        }
        setFailed(from === 'preview' ? { from } : { from, outputId: row.outputId });
      }
    });
  };

  const valueCell = (valueId: string) => {
    const display = displays.get(valueId);
    return display === undefined ? null : <Value display={display} layout="bare" />;
  };

  const columns: RegisterColumn<ReportRow>[] = [
    {
      kind: 'content',
      id: 'name',
      header: REP.columns.name,
      rowHeader: true,
      cell: (row) => {
        const name = displays.get(row.name);
        const superseded = row.superseded === null ? undefined : displays.get(row.superseded);
        return (
          <span className="flex min-w-[264px] items-start gap-3" id={`report-${row.outputId}`} data-report-row={row.outputId}>
            <FileText size={20} strokeWidth={1.5} aria-hidden="true" focusable="false" className="mt-0.5 shrink-0 text-(--sov-text-tertiary)" />
            {/* Balanced lines (DR-8): a long served name breaks once, near its middle, never inside its date. */}
            <span className="flex min-w-0 flex-col gap-1 break-words text-balance">
              {name === undefined ? null : <ValueName display={name} />}
              {superseded === undefined ? null : <StatusLine display={superseded} size="small" as="span" />}
            </span>
          </span>
        );
      },
    },
    // One line each (DR-8): a category and a date and time never wrap; who started it wraps instead.
    { kind: 'content', id: 'category', header: REP.columns.category, cell: (row) => <span className="text-[14px] whitespace-nowrap">{REP.categories[row.kind]}</span> },
    { kind: 'content', id: 'generatedAt', header: REP.columns.generatedAt, cell: (row) => <span className="block whitespace-nowrap" data-nowrap="">{valueCell(row.generatedAt)}</span> },
    { kind: 'content', id: 'generatedBy', header: REP.columns.generatedBy, cell: (row) => valueCell(row.generatedBy) },
  ];

  const empty =
    data === undefined ? null : data.view.state === 'none_generated' ? (
      <div className="flex flex-col items-start gap-3 py-6">
        <p className="sov-text-body">{REP.empty}</p>
        <Link to={pagePath(projectId, 'proposal')} className="sov-button" data-variant="link" data-size="default" data-icon="true" data-copy-kind="action-label">
          <span>{REP.emptyAction}</span>
          <ArrowRight size={16} strokeWidth={1.5} aria-hidden="true" focusable="false" />
        </Link>
      </div>
    ) : (
      <p className="sov-text-body py-6">{REP.noMatch}</p>
    );

  const supersededLine = selected === undefined || selected.superseded === null ? undefined : displays.get(selected.superseded);
  const preview =
    data === undefined || selected === undefined ? null : (
      <section aria-labelledby="report-preview" className="flex flex-col gap-4 rounded-(--sov-radius-surface) border border-(--sov-border) p-5" data-report-preview={selected.outputId}>
        <h2 id="report-preview" className="sov-text-caption tracking-[0.06em]">
          {REP.previewHeading}
        </h2>
        <Cover data={data} displays={displays} />
        <dl className="m-0 flex flex-col">
          <Detail name={REP.columns.name}>{valueCell(selected.name)}</Detail>
          <Detail name={REP.columns.category}>{REP.categories[selected.kind]}</Detail>
          <Detail name={REP.columns.generatedAt}>{valueCell(selected.generatedAt)}</Detail>
          <Detail name={REP.columns.generatedBy}>{valueCell(selected.generatedBy)}</Detail>
        </dl>
        {supersededLine === undefined ? null : <StatusLine display={supersededLine} />}
        <div className="flex flex-col gap-2">
          <Button variant="primary" icon={Download} aria-busy={downloading.busy} aria-describedby={failed?.from === 'preview' ? previewErrorId : undefined} onClick={() => download(selected, 'preview')}>
            {REP.download}
          </Button>
          {failed?.from === 'preview' ? (
            // Kept clear of the status footer when brought into view (its 48px and a gap: DR-4, DR-9).
            <div role="alert" className="scroll-mb-16" ref={previewAlert}>
              <FieldError id={previewErrorId} message={REP.downloadFailed} />
            </div>
          ) : null}
        </div>
      </section>
    );

  return (
    <div className="flex flex-col gap-6" data-reports-page="">
      <PageHeader eyebrow={REP.eyebrow} title={REP.title} subtitle={REP.subtitle} />
      <div className="grid grid-cols-[minmax(0,1fr)_300px] items-start gap-6">
        <div className="flex min-w-0 flex-col gap-4 [&>*]:min-w-0">
          <div className="flex flex-wrap items-center gap-3">
            <SearchField label={REP.searchLabel} placeholder={REP.searchPlaceholder} value={text} onChange={setText} />
            <ToolbarSelect
              label={REP.categoryLabel}
              value={query.category}
              options={[{ value: ALL, label: REP.allCategories }, ...OUTPUT_KINDS.map((kind) => ({ value: kind, label: REP.categories[kind] }))]}
              onChange={(category) => setQuery((previous) => ({ ...previous, category, page: 1 }))}
            />
            <div className="flex items-center gap-2">
              <ToolbarSelect
                label={REP.sortLabel}
                value={query.sort}
                options={[
                  { value: 'newest', label: REP.sortNewest },
                  { value: 'oldest', label: REP.sortOldest },
                ]}
                onChange={(sort) => setQuery((previous) => ({ ...previous, sort: sort === 'oldest' ? 'oldest' : 'newest', page: 1 }))}
              />
              <button
                type="button"
                className="sov-icon-button"
                aria-label={REP.sortDirection}
                onClick={() => setQuery((previous) => ({ ...previous, sort: previous.sort === 'newest' ? 'oldest' : 'newest', page: 1 }))}
              >
                <Icon icon={ArrowDownUp} size="small" />
              </button>
            </div>
          </div>
          <p role="status" aria-live="polite" className="sov-text-small">
            {downloading.busy ? REP.downloading : ''}
          </p>
          {failed?.from === 'row' ? (
            <div role="alert">
              <FieldError id={errorId} message={REP.downloadFailed} />
            </div>
          ) : null}
          {loading && data === undefined ? (
            <div className="border-t border-(--sov-border) py-5" data-loading-frame="reports">
              <Loading label={copy.app.loading} align="start" />
            </div>
          ) : null}
          {state.status === 'failed' && data === undefined ? <LoadFailed message={REP.loadFailed} onRetry={() => void reload()} /> : null}
          {data === undefined ? null : (
            <>
              <RegisterTable
                label={REP.tableLabel}
                columns={columns}
                rows={rows}
                rowKey={(row) => row.outputId}
                open={{ onOpen: (row) => setChosen(row.outputId), label: REP.showPreview, header: REP.columns.preview }}
                current={selected?.outputId ?? null}
                rowAction={{
                  header: REP.columns.download,
                  render: (row) => (
                    <button
                      type="button"
                      className="sov-icon-button"
                      aria-label={REP.download}
                      aria-describedby={failed?.from === 'row' && failed.outputId === row.outputId ? `report-${row.outputId} ${errorId}` : `report-${row.outputId}`}
                      aria-busy={downloading.busy}
                      onClick={() => download(row, 'row')}
                    >
                      <Icon icon={Download} size="small" />
                    </button>
                  ),
                }}
                controlsHeader={REP.columns.actions}
                empty={empty}
                busy={loading}
              />
              <Pager
                label={copy.workspace.pagination.label}
                previousLabel={copy.workspace.pagination.previous}
                nextLabel={copy.workspace.pagination.next}
                hasPrevious={data.view.page.hasPrevious}
                hasNext={data.view.page.hasNext}
                busy={loading}
                onPrevious={() => {
                  if (!loading) setQuery((previous) => ({ ...previous, page: Math.max(1, previous.page - 1) }));
                }}
                onNext={() => {
                  if (!loading) setQuery((previous) => ({ ...previous, page: previous.page + 1 }));
                }}
              />
            </>
          )}
        </div>
        {preview === null ? null : (
          <aside aria-label={REP.previewLabel} className="flex flex-col gap-4">
            {preview}
          </aside>
        )}
      </div>
    </div>
  );
}
