import { act, cleanup, fireEvent, screen, waitFor, within } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { ReportsResponseSchema } from '@sovitech/view-model/browser';
import { OUTPUT_A, OUTPUT_B, SUPERSEDED_TEXT, reportsResponse, type TestReport } from '../../../proposal/test-proposal';
import { PROJECT, heldHandler, installFakeApi, json, pressTwice, projectList, renderAt, sentTo, type Handler, type Seen } from '../../../test/harness';
import { frameResponse } from '../../test-views';
import { REPORTS_SEARCH_DELAY_MS } from './ReportsPage';

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
  vi.useRealTimers();
});

const LIST = `/api/projects/${PROJECT}/reports`;
const TWO: TestReport[] = [
  { outputId: OUTPUT_A, name: 'TEST preliminary proposal A', at: 'TEST 5 Oct 2026, 10:00', by: 'TEST demo account' },
  { outputId: OUTPUT_B, name: 'TEST preliminary proposal B', at: 'TEST 4 Oct 2026, 09:00', by: 'TEST demo account' },
];

function api(list: Handler, options: { readonly demo?: boolean } = {}, extra: Readonly<Record<string, Handler>> = {}) {
  return installFakeApi({
    'GET /api/projects': () => json(200, projectList([{ projectId: PROJECT, name: 'TEST project for reports', demo: options.demo === true }])),
    [`GET /api/projects/${PROJECT}/workspace`]: () => json(200, frameResponse(PROJECT, { demo: options.demo === true })),
    [`GET ${LIST}`]: list,
    ...extra,
  });
}

async function openPage() {
  const view = renderAt(`/projects/${PROJECT}/reports`);
  await screen.findByRole('heading', { name: 'Project Reports', level: 1 });
  await waitFor(() => expect(document.body.hasAttribute('data-render-ready')).toBe(true));
  return view;
}

function table() {
  return screen.getByRole('table', { name: 'Generated documents' });
}

function lastQuery(seen: readonly Seen[]): URLSearchParams {
  const last = seen.filter((request) => request.method === 'GET' && request.path === LIST).at(-1);
  if (last === undefined) throw new Error('no read of Reports');
  return last.url.searchParams;
}

function stubObjectUrls(): Blob[] {
  const created: Blob[] = [];
  vi.stubGlobal('URL', Object.assign(URL, { createObjectURL: (blob: Blob) => (created.push(blob), 'blob:TEST'), revokeObjectURL: () => undefined }));
  return created;
}

describe('DB-18 · R-119 · US-REPORTS-05 · US-REPORTS-14 AC1: Reports', () => {
  it('the TEST fixture is a response the contract accepts', () => {
    expect(() => ReportsResponseSchema.parse(reportsResponse(TWO))).not.toThrow();
  });

  it('US-REPORTS-05 AC1 AC7 AC13 · R-119 · R-120 · R-123 · 7.1.1-D8 · G2-1: each row shows its name, category, date and time and who started it, bound; no Status column, menu, "View", "+ Generate Report", templates, Compliance Report, page number or "Showing" line', async () => {
    api(() => json(200, reportsResponse(TWO, { hasNext: true, hasPrevious: true })));
    await openPage();
    const headers = within(table())
      .getAllByRole('columnheader')
      .map((cell) => cell.textContent);
    expect(headers).toEqual(['Name', 'Category', 'Date Generated', 'Generated By', 'Actions']);
    const row = within(table()).getByText('TEST preliminary proposal A').closest('tr') as HTMLElement;
    expect(within(row).getByText('TEST preliminary proposal A').closest('[data-value-id]')?.getAttribute('data-value-id')).toBe(`output:${OUTPUT_A}.name`);
    expect(within(row).getByText('Proposal')).toBeTruthy();
    expect(within(row).getByText('TEST 5 Oct 2026, 10:00').closest('[data-value-id]')?.getAttribute('data-value-id')).toBe(`output:${OUTPUT_A}.generatedAt`);
    expect(within(row).getByText('TEST demo account').closest('[data-value-id]')?.getAttribute('data-value-id')).toBe(`output:${OUTPUT_A}.generatedBy`);
    const text = document.body.textContent ?? '';
    for (const absent of ['Status', 'Generate Report', 'View All Templates', 'Compliance', 'Showing', 'Pages', 'File Size', 'BMS Live', 'CONFIDENTIAL', 'Ready']) expect(text).not.toContain(absent);
    expect(screen.queryByRole('button', { name: 'View' })).toBeNull();
    expect(screen.queryByRole('button', { name: 'More actions' })).toBeNull();
    // Previous and next only (proposal 7.2.30): no page number.
    const pager = screen.getByRole('navigation', { name: 'Pages' });
    expect(within(pager).getAllByRole('button').map((button) => button.textContent)).toEqual(['Previous', 'Next']);
  });

  it('US-REPORTS-05 AC5 AC9 AC10 AC11 · 7.1.1-E1 · OD-3 · OD-5: the preview fills with the first row, then with the row the owner picks; its cover names the project as stored (bound), "Preliminary proposal" and, on the demo, the demo line; no tagline or logo', async () => {
    api(() => json(200, reportsResponse(TWO, { demo: true })), { demo: true });
    await openPage();
    const preview = () => screen.getByRole('complementary', { name: 'Report preview' });
    expect(within(preview()).getAllByText('TEST preliminary proposal A').length).toBeGreaterThan(0);
    const cover = preview().querySelector('[data-report-cover]') as HTMLElement;
    expect(within(cover).getByText('TEST project for reports').closest('[data-value-id]')?.getAttribute('data-value-id')).toBe(`project:${PROJECT}.name`);
    expect(within(cover).getByText('Preliminary proposal')).toBeTruthy();
    expect(within(cover).getByText('TEST demo line')).toBeTruthy();
    expect(cover.querySelector('img, svg, canvas')).toBeNull();
    const rowB = within(table()).getByText('TEST preliminary proposal B').closest('tr') as HTMLElement;
    fireEvent.click(within(rowB).getByRole('button', { name: 'Show preview' }));
    await waitFor(() => expect(within(preview()).getAllByText('TEST preliminary proposal B').length).toBeGreaterThan(0));
    expect(rowB.getAttribute('aria-current')).toBe('true');
  });

  it('US-REPORTS-05 AC14 (its search, filter and sort; R-119) · G2-1: the search is sent a moment after the last key, the category and the sort go to the list query, the direction toggle flips the sort, and Next asks for the next page; nothing is written', async () => {
    const seen = api(() => json(200, reportsResponse(TWO, { hasNext: true })));
    await openPage();
    vi.useFakeTimers({ shouldAdvanceTime: true });
    fireEvent.change(screen.getByRole('searchbox', { name: 'Search reports' }), { target: { value: 'TEST A' } });
    expect(lastQuery(seen).get('search')).toBeNull();
    await act(async () => {
      await vi.advanceTimersByTimeAsync(REPORTS_SEARCH_DELAY_MS + 10);
    });
    await waitFor(() => expect(lastQuery(seen).get('search')).toBe('TEST A'));
    vi.useRealTimers();
    fireEvent.change(screen.getByRole('combobox', { name: 'Category' }), { target: { value: 'proposal_pdf' } });
    await waitFor(() => expect(lastQuery(seen).get('category')).toBe('proposal_pdf'));
    fireEvent.click(screen.getByRole('button', { name: 'Change the sort direction' }));
    await waitFor(() => expect(lastQuery(seen).get('sort')).toBe('oldest'));
    expect((screen.getByRole('combobox', { name: 'Sort' }) as HTMLSelectElement).value).toBe('oldest');
    await waitFor(() => expect(document.body.hasAttribute('data-render-ready')).toBe(true));
    fireEvent.click(screen.getByRole('button', { name: 'Next' }));
    await waitFor(() => expect(lastQuery(seen).get('page')).toBe('2'));
    expect(seen.filter((request) => request.method !== 'GET')).toHaveLength(0);
  });

  it('R-119 · rule 7: with nothing generated yet the register says what to do, with the way to the Proposal page; with nothing matching it says so', async () => {
    api(() => json(200, reportsResponse([])));
    const view = await openPage();
    expect(screen.getByText('No document has been generated yet. Download your preliminary proposal from the Proposal page and it is listed here.')).toBeTruthy();
    expect(screen.queryByRole('complementary', { name: 'Report preview' })).toBeNull();
    const main = screen.getByRole('main');
    fireEvent.click(within(main).getByRole('link', { name: 'Open the Proposal page' }));
    await waitFor(() => expect(view.router.state.location.pathname).toBe(`/projects/${PROJECT}/proposal`));
    cleanup();
    api(() => json(200, reportsResponse([], { state: 'listed' })));
    await openPage();
    expect(screen.getByText('No report matches the search or the category.')).toBeTruthy();
  });

  it('G10-2 · US-REPORTS-05 AC15 (the PRD\'s interim): a row whose snapshot\'s quotation record went stale shows "Superseded: inputs changed on <date>", bound, on its row and beside the preview\'s download', async () => {
    api(() => json(200, reportsResponse([{ ...TWO[0], superseded: true } as TestReport])));
    await openPage();
    const row = within(table()).getByText('TEST preliminary proposal A').closest('tr') as HTMLElement;
    expect(within(row).getByText(SUPERSEDED_TEXT).closest('[data-value-id]')?.getAttribute('data-value-id')).toBe(`output:${OUTPUT_A}.superseded`);
    expect(within(screen.getByRole('complementary', { name: 'Report preview' })).getByText(SUPERSEDED_TEXT)).toBeTruthy();
  });

  it('US-REPORTS-05 AC6 · docs/adr/0050 decision 3 · rule 7: a row\'s download and the preview\'s Download read the stored output\'s file, one request per press, never disabled; a failure says so', async () => {
    const created = stubObjectUrls();
    const held = heldHandler(() => new Response('%PDF-TEST', { status: 200, headers: { 'content-type': 'application/pdf', 'content-disposition': 'attachment; filename="TEST-A.pdf"' } }));
    const seen = api(() => json(200, reportsResponse(TWO)), {}, {
      [`GET /api/projects/${PROJECT}/exports/${OUTPUT_A}/file`]: held.handler,
      [`GET /api/projects/${PROJECT}/exports/${OUTPUT_B}/file`]: () => json(503, { code: 'export_unavailable' }),
    });
    await openPage();
    const rowA = within(table()).getByText('TEST preliminary proposal A').closest('tr') as HTMLElement;
    const download = within(rowA).getByRole('button', { name: 'Download' });
    pressTwice(download);
    expect(download.hasAttribute('disabled')).toBe(false);
    await screen.findByText('Preparing the document');
    held.answer();
    await waitFor(() => expect(created).toHaveLength(1));
    expect(sentTo(seen, 'GET', `/exports/${OUTPUT_A}/file`)).toBe(1);
    expect(seen.filter((request) => request.method === 'POST')).toHaveLength(0);
    const rowB = within(table()).getByText('TEST preliminary proposal B').closest('tr') as HTMLElement;
    await waitFor(() => expect(download.getAttribute('aria-busy')).toBe('false'));
    fireEvent.click(within(rowB).getByRole('button', { name: 'Download' }));
    await screen.findByText('The document could not be prepared. Try again.');
  });

  it('DR-9 · rule 7: a failed download says so beside the control that was pressed: under the preview\'s Download, which it describes; under the toolbar for a row\'s button, which it then describes, beside the row\'s name', async () => {
    stubObjectUrls();
    api(() => json(200, reportsResponse(TWO)), {}, {
      [`GET /api/projects/${PROJECT}/exports/${OUTPUT_A}/file`]: () => json(503, { code: 'export_unavailable' }),
      [`GET /api/projects/${PROJECT}/exports/${OUTPUT_B}/file`]: () => json(503, { code: 'export_unavailable' }),
    });
    await openPage();
    const preview = screen.getByRole('complementary', { name: 'Report preview' });
    const previewDownload = within(preview).getByRole('button', { name: 'Download' });
    fireEvent.click(previewDownload);
    const message = await within(preview).findByText('The document could not be prepared. Try again.');
    const messageId = message.closest('[id]')?.id ?? '';
    expect(previewDownload.getAttribute('aria-describedby')).toBe(messageId);
    // Right under the button it describes, in the same box.
    expect(previewDownload.parentElement?.contains(message)).toBe(true);
    expect(screen.getAllByText('The document could not be prepared. Try again.')).toHaveLength(1);
    await waitFor(() => expect(previewDownload.getAttribute('aria-busy')).toBe('false'));
    const rowB = within(table()).getByText('TEST preliminary proposal B').closest('tr') as HTMLElement;
    const rowDownload = within(rowB).getByRole('button', { name: 'Download' });
    fireEvent.click(rowDownload);
    await waitFor(() => expect(within(preview).queryByText('The document could not be prepared. Try again.')).toBeNull());
    const rowMessage = await screen.findByText('The document could not be prepared. Try again.');
    expect(preview.contains(rowMessage)).toBe(false);
    expect(rowDownload.getAttribute('aria-describedby')?.split(' ')).toEqual([`report-${OUTPUT_B}`, rowMessage.closest('[id]')?.id]);
    const rowA = within(table()).getByText('TEST preliminary proposal A').closest('tr') as HTMLElement;
    expect(within(rowA).getByRole('button', { name: 'Download' }).getAttribute('aria-describedby')).toBe(`report-${OUTPUT_A}`);
  });

  it('DR-7 · DB-18: the control columns are headed by one visible "Actions"; the preview column is never headed "Name"; each control names itself and is described by its row\'s name', async () => {
    api(() => json(200, reportsResponse(TWO)));
    await openPage();
    const actions = within(table()).getByRole('columnheader', { name: 'Actions' });
    expect(actions.getAttribute('colspan')).toBe('2');
    expect(actions.querySelector('.sov-visually-hidden')).toBeNull();
    expect(within(table()).getAllByRole('columnheader', { name: 'Name' })).toHaveLength(1);
    const rowA = within(table()).getByText('TEST preliminary proposal A').closest('tr') as HTMLElement;
    for (const name of ['Show preview', 'Download']) {
      const describedBy = within(rowA).getByRole('button', { name }).getAttribute('aria-describedby') ?? '';
      expect(document.getElementById(describedBy)?.textContent).toContain('TEST preliminary proposal A');
    }
  });

  it('DR-8: Category and Date Generated keep one line, Name keeps a minimum width and balances its lines, and Generated By may wrap', async () => {
    api(() => json(200, reportsResponse([{ ...TWO[0], by: 'TEST demo seed (demo input, not a person)' } as TestReport])));
    await openPage();
    const row = within(table()).getByText('TEST preliminary proposal A').closest('tr') as HTMLElement;
    const cells = [...row.children] as HTMLElement[];
    expect(cells[1]?.querySelector('.whitespace-nowrap')?.textContent).toBe('Proposal');
    expect(cells[2]?.querySelector('[data-nowrap]')?.className).toContain('whitespace-nowrap');
    expect(cells[2]?.querySelector('[data-nowrap]')?.textContent).toContain('TEST 5 Oct 2026, 10:00');
    expect(cells[3]?.querySelector('.whitespace-nowrap')).toBeNull();
    expect(row.querySelector('[data-report-row]')?.className).toMatch(/\bmin-w-\[\d+px\]/u);
    // A long served name breaks once, near its middle, so its date and time stay together (balanced lines).
    expect(within(row).getByText('TEST preliminary proposal A').closest('.text-balance')).not.toBeNull();
  });

  it('DR-10 · DR-4 · OD-2 · 7.1.1-E1: the preview\'s cover draws the PDF cover\'s parts in the PDF\'s order (the title, the project\'s name bound, the demo line), with no logo or wordmark; it is capped in width so the details and Download follow it, Download full width', async () => {
    api(() => json(200, reportsResponse(TWO, { demo: true })), { demo: true });
    await openPage();
    const preview = screen.getByRole('complementary', { name: 'Report preview' });
    const cover = preview.querySelector('[data-report-cover]') as HTMLElement;
    const parts = [...cover.querySelectorAll('[data-cover-title], [data-cover-project], [data-cover-demo-line]')].map((part) => part.textContent);
    expect(parts).toEqual(['Preliminary proposal', 'TEST project for reports', 'TEST demo line']);
    expect(cover.querySelector('[data-cover-project] [data-value-id]')?.getAttribute('data-value-id')).toBe(`project:${PROJECT}.name`);
    expect(cover.textContent).not.toMatch(/SOVITECH|Building automation|CONFIDENTIAL/u);
    expect(cover.querySelector('img, svg, canvas')).toBeNull();
    expect(cover.className).toMatch(/max-w-\[210px\]/u);
    // The details' names take a narrow column, and Download follows them, stretched to the preview's width.
    expect(preview.querySelector('dl > div')?.className).toContain('grid-cols-[96px_minmax(0,1fr)]');
    const download = within(preview).getByRole('button', { name: 'Download' });
    expect(cover.compareDocumentPosition(download) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
  });

  it('DR-13: with nothing generated yet, the way to the Proposal page reads "Open the Proposal page", styled as the other in-page links, with its arrow', async () => {
    api(() => json(200, reportsResponse([])));
    await openPage();
    const link = within(screen.getByRole('main')).getByRole('link', { name: 'Open the Proposal page' });
    expect(link.getAttribute('data-variant')).toBe('link');
    expect(link.getAttribute('data-icon')).toBe('true');
    expect(link.querySelector('svg[aria-hidden="true"]')).not.toBeNull();
    expect(link.getAttribute('href')).toBe(`/projects/${PROJECT}/proposal`);
  });

  it('rule 7 · R-003: a register that cannot be loaded says so and offers "Try again"', async () => {
    let calls = 0;
    api(() => {
      calls += 1;
      return calls === 1 ? json(500, { code: 'internal_error' }) : json(200, reportsResponse(TWO));
    });
    await openPage();
    expect(screen.getByText('Your reports could not be loaded. Try again.')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Try again' }));
    await screen.findByRole('table', { name: 'Generated documents' });
  });

  it('G10-10 · GS-1 (web side): the demo line shows on Reports of the demo project and not on another project', async () => {
    api(() => json(200, reportsResponse(TWO, { demo: true })), { demo: true });
    await openPage();
    expect(screen.getAllByText('TEST demo line').length).toBeGreaterThan(0);
    cleanup();
    api(() => json(200, reportsResponse(TWO)));
    await openPage();
    expect(screen.queryByText('TEST demo line')).toBeNull();
  });
});
