/**
 * The demo project's owner answers (prompt 3 section 7, "The demo is labelled and sourced":
 * "The demo's owner answers (the four required fields, and steps 4 to 7) are `user`
 * candidates that the seed writes from a committed fixture file, under a seed user labelled
 * as demo input"; guardrails rule 10, "Demo data"; 2.1, `user`; F-INGEST-09;
 * docs/adr/0029-demo-seed.md).
 *
 * The file is fixtures/demo/owner-answers.json (generated by fixtures/demo/generate.ts and
 * listed in fixtures/manifest.json). It is read as data and checked against the production
 * field registry before anything is written, so it can only ever hold what an owner could
 * answer on those steps:
 * - a field of step 1 (rule 7's four required fields, all four present), step 4 (a system in
 *   scope), step 5 (building type, occupancy, operating schedule), step 6 (a goal) or step 7
 *   (an automation area), each at most once, and each multi-select of steps 4, 6 and 7
 *   answered for every option (a multi-select's Continue decides each option it shows);
 * - on a field the owner confirms (`confirmBy` owner: rule 3, "The owner confirms facts they
 *   know" and "their own choices"), so never an engineer's field: no area, count, rating or
 *   protocol, and so no engineering value and no figure (rule 1);
 * - a choice among the field's options, or a text for a text field; the project name is the
 *   demo's working name (OD-5; US-ADMIN-15 AC1) and the country an ISO 3166-1 code.
 *
 * Each answer becomes one `user` candidate in the seed account's name with its
 * `user_confirmed` event (2.1: "The owner's own entry on a field whose `confirmBy` is `owner`
 * or `either` gets a `user_confirmed` event when it is created"). The store accepts both only
 * because the seed account acts as the owner on a demo project, and nowhere else (0006,
 * `request_user_acts_as`; 0009, the candidate and event guards). Nothing is marked accepted
 * from a suggestion: the seed shows no screen, so nothing was suggested (rule 3).
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { appendCandidateEvent, ensureBuildingSubject, insertCandidate, newId, projectOf, type Request } from '@sovitech/db';
import { AUTOMATION_FIELDS, FIELD, GOAL_FIELDS, SCOPE_FIELDS, productionRegistry, registryLookups } from '@sovitech/registry';
import { parse } from 'yaml';
import { z } from 'zod';

/** The committed fixture file, from the repository root. */
export const OWNER_ANSWERS_PATH = 'fixtures/demo/owner-answers.json';
export const OWNER_ANSWERS_FORMAT = 'sovitech-demo-owner-answers/1';
/** The demo's working name (OD-5; guardrails rule 10, "Demo data"). */
export const DEMO_WORKING_NAME = 'Demo Hotel Bucharest';
/** The reason every answer's `user_confirmed` event carries: demo input, not a person's. */
export const DEMO_INPUT_REASON = 'demo_input';

export type WizardStep = 1 | 4 | 5 | 6 | 7;

const AnswerSchema = z.strictObject({
  step: z.union([z.literal(1), z.literal(4), z.literal(5), z.literal(6), z.literal(7)]),
  fieldKey: z.string().min(1),
  choice: z.string().min(1).optional(),
  text: z.string().min(1).optional(),
});

const FileSchema = z.strictObject({
  format: z.literal(OWNER_ANSWERS_FORMAT),
  about: z.string().min(1),
  answers: z.array(AnswerSchema).min(1),
});

/** One answer, checked against the registry: its field, the subject it belongs to, and its value. */
export interface PlannedAnswer {
  readonly step: WizardStep;
  readonly fieldKey: string;
  readonly subject: 'project' | 'building';
  readonly value: { readonly choice: string } | { readonly text: string };
}

export class DemoAnswersError extends Error {
  override name = 'DemoAnswersError';

  constructor(readonly problems: readonly string[]) {
    super(`The demo's owner answers (${OWNER_ANSWERS_PATH}) were refused:\n${problems.join('\n')}`);
  }
}

const lookups = registryLookups(productionRegistry);
const STEP_5: readonly string[] = [FIELD.buildingType, FIELD.occupancy, FIELD.operatingSchedule];
const MULTI_SELECT: ReadonlyMap<WizardStep, readonly string[]> = new Map<WizardStep, readonly string[]>([
  [4, SCOPE_FIELDS],
  [6, GOAL_FIELDS],
  [7, AUTOMATION_FIELDS],
]);

/** The wizard step that asks the owner for a field, or undefined when no step 1, 4, 5, 6 or 7 question does. */
export function ownerStepOf(fieldKey: string): WizardStep | undefined {
  const field = lookups.field(fieldKey);
  if (field === undefined) return undefined;
  if (field.criticality === 'required') return 1;
  if (SCOPE_FIELDS.includes(fieldKey)) return 4;
  if (STEP_5.includes(fieldKey)) return 5;
  if (GOAL_FIELDS.includes(fieldKey)) return 6;
  if (AUTOMATION_FIELDS.includes(fieldKey)) return 7;
  return undefined;
}

/** Checks the file's content against the registry; returns the answers to write, or throws with every problem. */
export function planOwnerAnswers(content: unknown): readonly PlannedAnswer[] {
  const parsed = FileSchema.safeParse(content);
  if (!parsed.success) {
    throw new DemoAnswersError([...new Set(parsed.error.issues.map((issue) => `${issue.path.map(String).join('.') || '(root)'}: ${issue.message}`))]);
  }
  const problems: string[] = [];
  const planned: PlannedAnswer[] = [];
  const seen = new Set<string>();
  for (const [index, answer] of parsed.data.answers.entries()) {
    const where = `answers.${index} (${answer.fieldKey})`;
    const field = lookups.field(answer.fieldKey);
    if (field === undefined) {
      problems.push(`${where}: not a field of the production registry`);
      continue;
    }
    if (seen.has(field.key)) problems.push(`${where}: answered twice`);
    seen.add(field.key);
    const step = ownerStepOf(field.key);
    if (step === undefined) problems.push(`${where}: no step 1, 4, 5, 6 or 7 question asks the owner for it`);
    else if (step !== answer.step) problems.push(`${where}: asked on step ${step}, not step ${answer.step}`);
    if (field.confirmBy !== 'owner') problems.push(`${where}: confirmBy is ${field.confirmBy}; the owner answers only fields the owner confirms (rule 3)`);
    if (field.subject !== 'project' && field.subject !== 'building') problems.push(`${where}: a ${field.subject} field is no owner answer`);
    let value: PlannedAnswer['value'] | undefined;
    if (field.kind === 'text') {
      if (answer.text === undefined || answer.choice !== undefined || answer.text.trim() !== answer.text) problems.push(`${where}: a text field takes one trimmed text`);
      else value = { text: answer.text };
    } else if (field.kind === 'enum' || field.kind === 'decision') {
      if (answer.choice === undefined || answer.text !== undefined) problems.push(`${where}: an ${field.kind} field takes one choice`);
      else if (!(field.options ?? []).includes(answer.choice)) problems.push(`${where}: "${answer.choice}" is not among the field's options`);
      else value = { choice: answer.choice };
    } else {
      problems.push(`${where}: a ${field.kind} field is an engineering value, never an owner answer from this file (rule 1)`);
    }
    if (field.key === FIELD.projectName && value !== undefined && (!('text' in value) || value.text !== DEMO_WORKING_NAME)) {
      problems.push(`${where}: the demo project is named "${DEMO_WORKING_NAME}" (OD-5)`);
    }
    if (field.key === FIELD.country && value !== undefined && (!('text' in value) || !/^[A-Z]{2}$/u.test(value.text))) {
      problems.push(`${where}: the country is an ISO 3166-1 alpha-2 code`);
    }
    if (step !== undefined && value !== undefined && (field.subject === 'project' || field.subject === 'building')) {
      planned.push({ step, fieldKey: field.key, subject: field.subject, value });
    }
  }
  for (const field of productionRegistry.fields) {
    if (field.criticality === 'required' && !seen.has(field.key)) problems.push(`${field.key}: a step 1 field is not answered (rule 7: the project needs all four)`);
  }
  for (const [step, keys] of MULTI_SELECT) {
    const missing = keys.filter((key) => !seen.has(key));
    if (missing.length > 0) problems.push(`step ${step}: every option of the multi-select is answered; missing ${missing.join(', ')}`);
  }
  if (problems.length > 0) throw new DemoAnswersError(problems);
  return planned;
}

/** Reads and checks the committed file under the repository root. */
export function readOwnerAnswers(repositoryRoot: string): readonly PlannedAnswer[] {
  const text = readFileSync(join(repositoryRoot, OWNER_ANSWERS_PATH), 'utf8');
  // Read with the YAML reader restricted to its JSON schema (JSON.parse is reserved for the
  // reviewed readers: the lint ban no-json-parse); the schema check follows at once.
  return planOwnerAnswers(parse(text, { schema: 'json', maxAliasCount: 0, uniqueKeys: true }) as unknown);
}

/** One answer as stored: the candidate and its `user_confirmed` event. */
export interface WrittenAnswer {
  readonly step: WizardStep;
  readonly fieldKey: string;
  readonly subjectId: string;
  readonly candidateId: string;
}

/**
 * Writes answers in the seed account's own request on the demo project: each a `user`
 * candidate with its `user_confirmed` event, in the owner's role. The store refuses both
 * anywhere but a demo project, and from any account but the seed that holds `owner` there.
 */
export async function writeOwnerAnswers(request: Request, input: { readonly seedId: string; readonly answers: readonly PlannedAnswer[] }): Promise<WrittenAnswer[]> {
  const projectId = projectOf(request);
  const buildingId = input.answers.some((answer) => answer.subject === 'building') ? await ensureBuildingSubject(request, input.seedId) : undefined;
  const written: WrittenAnswer[] = [];
  for (const answer of input.answers) {
    const field = lookups.field(answer.fieldKey);
    if (field === undefined) throw new Error(`${answer.fieldKey} is not a registry field`);
    const subjectId = answer.subject === 'building' ? buildingId : projectId;
    if (subjectId === undefined) throw new Error('the building subject was not created');
    const candidateId = newId();
    const stored = await insertCandidate(
      request,
      { id: candidateId, subjectId, fieldKey: field.key, ...answer.value, source: 'user', evidence: [], createdBy: input.seedId },
      field,
    );
    if (stored.outcome !== 'stored') throw new Error(`the store refused the demo answer on ${field.key} (${stored.outcome})`);
    await appendCandidateEvent(request, { candidateId, type: 'user_confirmed', by: input.seedId, role: 'owner', reason: DEMO_INPUT_REASON });
    written.push({ step: answer.step, fieldKey: field.key, subjectId, candidateId });
  }
  return written;
}
