/**
 * Generator of the demo project's owner answers (prompt 3 section 7, "The demo is
 * labelled and sourced": "The demo's owner answers (the four required fields, and steps
 * 4 to 7) are `user` candidates that the seed writes from a committed fixture file, under
 * a seed user labelled as demo input").
 *
 *   tsx fixtures/demo/generate.ts --out <folder>
 *
 * writes <folder>/fixtures/demo/owner-answers.json; `--out .` from the repository root
 * rewrites the committed file. The fixture-manifest check runs it into a temporary
 * folder and compares the bytes with fixtures/manifest.json.
 *
 * What the file holds: the answers a fictional owner gives on steps 1, 4, 5, 6 and 7 of
 * the wizard for the demo project, working name "Demo Hotel Bucharest" (OD-5; guardrails
 * rule 10, "Demo data"). The demo seed (apps/api/src/seed/) reads it, checks every answer
 * against the production field registry, and writes each one as a `user` candidate with
 * its `user_confirmed` event, in the name of the demo seed account.
 *
 * What it never holds: an engineering value (an area, a count, a rating, a price), which
 * comes only from documents, calculation or an engineer (rule 1), and so no figure; a
 * suggestion or a preselection (rule 3: the seed renders no screen, so nothing is
 * "accepted"); the real hotel's name the mockups show (OD-5); anything from the mockups'
 * figures, the specs or company/.
 *
 * The choices follow the approved step 8 summary's kinds of answer, made consistent where
 * the mockups contradict themselves (onboarding-spec 6.1): the project type is the step 8
 * summary's, and the automation areas follow the systems in scope and the goals (the
 * mockups leave Energy Management unchecked although Energy is in scope, a slip listed in
 * 6.1). Fire Safety is left out of scope, as on the approved step 4: its fire-alarm input
 * and fire-mode status stay in the point list whatever the owner chooses (G11-3).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

/** One owner answer: the wizard step, the registry field, and the choice or text the owner gave. */
export interface DemoOwnerAnswer {
  readonly step: 1 | 4 | 5 | 6 | 7;
  readonly fieldKey: string;
  readonly choice?: string;
  readonly text?: string;
}

export interface DemoOwnerAnswers {
  readonly format: 'sovitech-demo-owner-answers/1';
  readonly about: string;
  readonly answers: readonly DemoOwnerAnswer[];
}

const choice = (step: DemoOwnerAnswer['step'], fieldKey: string, value: string): DemoOwnerAnswer => ({ step, fieldKey, choice: value });
const text = (step: DemoOwnerAnswer['step'], fieldKey: string, value: string): DemoOwnerAnswer => ({ step, fieldKey, text: value });

export const DEMO_OWNER_ANSWERS: DemoOwnerAnswers = {
  format: 'sovitech-demo-owner-answers/1',
  about:
    'TEST fixture: the owner answers of the demo project, a fictitious hotel (working name Demo Hotel Bucharest). Demo input written by the demo seed as user candidates of the seed account; not a real owner and not a real building. Generated by fixtures/demo/generate.ts.',
  answers: [
    // Step 1: rule 7's four required fields (project name, project type, city, country). Country first (prompt 3 5.2).
    text(1, 'project.name', 'Demo Hotel Bucharest'),
    choice(1, 'project.type', 'renovation'),
    text(1, 'project.country', 'RO'),
    text(1, 'project.city', 'Bucharest'),
    // Step 4: the systems in scope, one decision per system (2.6). Fire Safety stays opt-in and is left out (rule 11).
    choice(4, 'project.scope.hvac', 'include'),
    choice(4, 'project.scope.lighting', 'include'),
    choice(4, 'project.scope.energy', 'include'),
    choice(4, 'project.scope.access_control', 'include'),
    choice(4, 'project.scope.fire_safety', 'exclude'),
    choice(4, 'project.scope.water', 'exclude'),
    choice(4, 'project.scope.elevators', 'exclude'),
    choice(4, 'project.scope.cctv', 'exclude'),
    // Step 5: the building type (a fact the owner knows, rule 3), occupancy and the operating schedule.
    choice(5, 'building.type', 'hotel'),
    choice(5, 'project.occupancy', 'mostly_occupied'),
    choice(5, 'project.operatingSchedule', '24_7'),
    // Step 6: the goals, one decision per goal.
    choice(6, 'project.goal.reduce_energy', 'selected'),
    choice(6, 'project.goal.lower_carbon', 'not_selected'),
    choice(6, 'project.goal.occupant_comfort', 'selected'),
    choice(6, 'project.goal.operational_efficiency', 'not_selected'),
    choice(6, 'project.goal.compliance', 'not_selected'),
    choice(6, 'project.goal.asset_lifespan', 'not_selected'),
    choice(6, 'project.goal.reduce_operating_costs', 'selected'),
    // Step 7: the automation areas, one decision per area.
    choice(7, 'project.automation.hvac', 'selected'),
    choice(7, 'project.automation.lighting', 'selected'),
    choice(7, 'project.automation.energy_management', 'selected'),
    choice(7, 'project.automation.water_management', 'not_selected'),
    choice(7, 'project.automation.security_access', 'not_selected'),
    choice(7, 'project.automation.predictive_maintenance', 'not_selected'),
  ],
};

function main(argv: readonly string[]): void {
  const at = argv.indexOf('--out');
  const out = at < 0 ? undefined : argv[at + 1];
  if (out === undefined) throw new Error('usage: tsx fixtures/demo/generate.ts --out <folder>');
  const folder = join(out, 'fixtures', 'demo');
  mkdirSync(folder, { recursive: true });
  writeFileSync(join(folder, 'owner-answers.json'), `${JSON.stringify(DEMO_OWNER_ANSWERS, null, 2)}\n`);
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) main(process.argv.slice(2));
