/**
 * Proposed behaviour, not indexed (prompt 3 sections 5.4, 8 and 10, phase 2;
 * docs/adr/0034-streamed-ifc-output-and-sandbox-bounds.md): the per-line form of the sealed IFC
 * section, written by the IFC reader's command line and read line by line by the API's worker,
 * with `ifc-values` (and, for the proposals, the gates of their mechanisms) opened by the
 * test-utils override. It waits for what the value path waits for: ifc-input 6.2.1, 6.2.2, 6.2.3
 * and 6.2.10 (the `ifc-values` gate), the approved IFC mapping tables and the owner's revision of
 * build-readiness decision 4.
 *
 * - The round trip: for each of the four fixture models, the lines the command line writes read
 *   back, through the worker's reading (apps/api/src/jobs/output-file.ts), to the same output and
 *   the same opened section as the job's in-memory output.
 * - The refusals: a line cut short, too long, not JSON, refused by the contract, out of order,
 *   missing or one too many refuses the whole output, with a named code.
 * - The worker: a refused line stores nothing of the output; and the `perf` model (git-ignored,
 *   generated by the fixtures' perf profile: 101 MB, 1,457,649 instances, 157,166 elements),
 *   whose section was refused as `output.too_large` before, runs through the whole path with the
 *   gate open: the reader's command line in its own process (as in its sandbox, with its 2 GB
 *   V8 heap), the worker's line-by-line reading, and the gated value path's storing (ADR 0033).
 *   Its times and peak memory are printed for ADR 0034.
 *
 * Every account, project, field and table is TEST data; the models are the generated synthetic
 * fixtures (fixtures/ifc/), and the perf model is the perf profile's output (never in the
 * manifest; this suite's upload guard takes its hash besides the manifest's).
 *
 * Ids: ifc-input 5.4 IFC-1 (the locator each fact carries); R-027 (sealed); F-INGEST-04 (the
 * worker), F-IFC-03 and F-IFC-04 (gated).
 */
import { spawn } from 'node:child_process';
import { copyFileSync, existsSync, linkSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { parse } from 'yaml';
import { readDocumentTexts, readIfcElements, readModelRecords, withRequest } from '@sovitech/db';
import { IFC_VALUES_LINE_MAX_BYTES, openIfcValues, parseExtractionOutput, type ExtractionOutput, type ExtractionRequest } from '@sovitech/extraction-contract';
import { checkedRequest, contentHashOf, main as readIfc, runIfcJob } from '@sovitech/ifc-reader';
import { REPO_ROOT, type GateId, type GateSource } from '@sovitech/registry/gates';
import { openGateForTest } from '@sovitech/registry/test-utils';
import { EXTRACTION_LIMITS } from '../../apps/api/src/ingestion/extraction';
import { readJobOutput } from '../../apps/api/src/jobs/output-file';
import type { ExtractorRunner, SandboxJob, SandboxOutcome } from '../../apps/api/src/jobs/sandbox';
import { AnalysisWorker } from '../../apps/api/src/jobs/worker';
import { fixtureUploadGuard } from '../../apps/api/src/uploads/fixture-guard';
import { ownerWithProject, signIn, startTestApi, upload, type TestApi } from '../guardrails/_support/api';

const WORK = mkdtempSync(join(tmpdir(), 'sovitech-proposed-ifc-stream-'));
const DATASET = { id: 'TEST-ifc-mapping', version: '0.0.1' };
const MODELS = ['demo-hotel-arh', 'demo-hotel-mep-rev-a', 'demo-hotel-mep-rev-b', 'demo-hotel-mep-ifc2x3'] as const;
const PERF = join(REPO_ROOT, 'fixtures/ifc/perf/demo-hotel-perf.ifc');

/** A TEST mapping table: synthetic field keys and choices, for this suite only (no SOVITECH table exists). */
const TEST_RULES = [
  { id: 'tag', mechanism: 'tag_source', fieldKey: 'asset.testTag', subjectKind: 'asset', sourceClaim: 'document', match: { attribute: 'Tag', requireLetter: true }, value: { kind: 'fact' } },
  { id: 'location', mechanism: 'relation', fieldKey: 'asset.testLocation', subjectKind: 'asset', sourceClaim: 'document', match: { relation: 'contained_in_spatial_structure' }, value: { kind: 'fact' } },
  { id: 'chiller', mechanism: 'direct_read', fieldKey: 'asset.testCoolingOutput', subjectKind: 'asset', sourceClaim: 'document', match: { propertySet: 'Pset_ChillerTypeCommon', property: 'ChillerCapacity' }, value: { kind: 'fact' } },
  { id: 'net-area', mechanism: 'quantity_set_area', fieldKey: 'zone.testArea', subjectKind: 'zone', sourceClaim: 'document', match: { objectKind: 'space', quantitySet: 'Qto_SpaceBaseQuantities', quantity: 'NetFloorArea' }, value: { kind: 'fact' } },
  { id: 'cta', mechanism: 'name_term', fieldKey: 'asset.testType', subjectKind: 'asset', sourceClaim: 'ai_inference', confidence: 'high', match: { tagPrefix: 'CTA' }, value: { kind: 'choice', choice: 'test_ahu' } },
];

/** `ifc-values` and the gates the TEST table's mechanisms wait for, opened by the test-utils override (only inside a hook or a test). */
function openGates(): GateSource {
  const more: readonly GateId[] = ['ifc-identity', 'ifc-code-inference', 'dataset-glossary', 'ifc-areas'];
  return more.reduce<GateSource>((source, id) => openGateForTest(id, source), openGateForTest('ifc-values'));
}

const JOB_PROJECT = '0192f0a0-0000-7000-8000-00000000c501';

interface Written {
  readonly path: string;
  readonly request: ExtractionRequest;
  readonly inMemory: ExtractionOutput;
}

/** The reader's command line on a model, IFC values asked for with the TEST table mounted, and the same job in memory. */
async function written(model: string, label: string): Promise<Written> {
  const bytes = readFileSync(join(REPO_ROOT, 'fixtures/ifc', `${model}.ifc`));
  const folder = join(WORK, label);
  mkdirSync(join(folder, 'datasets'), { recursive: true });
  mkdirSync(join(folder, 'out'), { recursive: true });
  writeFileSync(join(folder, 'datasets', `${DATASET.id}@${DATASET.version}.json`), JSON.stringify({ ...DATASET, kind: 'ifc-mapping', rules: TEST_RULES }));
  const request = checkedRequest({
    contractVersion: '1.0.0',
    job: { projectId: JOB_PROJECT, documentId: '0192f0a0-0000-7000-8000-00000000c502', contentHash: contentHashOf(bytes) },
    declaredFormat: 'ifc',
    ifcValues: true,
    datasets: [DATASET],
    derivatives: [],
    limits: EXTRACTION_LIMITS,
  });
  writeFileSync(join(folder, 'request.json'), JSON.stringify(request));
  const status = await readIfc(
    ['--request', join(folder, 'request.json'), '--document', join(REPO_ROOT, 'fixtures/ifc', `${model}.ifc`), '--out', join(folder, 'out'), '--datasets', join(folder, 'datasets')],
    () => undefined,
  );
  if (status !== 0) throw new Error(`the reader's command line exited ${String(status)}`);
  const inMemory = await runIfcJob(request, bytes, { datasets: join(folder, 'datasets') });
  return { path: join(folder, 'out', 'output.json'), request, inMemory };
}

/** A copy of an output file's lines, changed by `edit`, written beside it. */
let copies = 0;
function edited(source: Written, edit: (lines: string[]) => string[] | string): string {
  const text = readFileSync(source.path, 'utf8');
  const lines = text.slice(0, -1).split('\n');
  const changed = edit(lines);
  copies += 1;
  const path = join(WORK, `edited-${String(copies)}.json`);
  writeFileSync(path, typeof changed === 'string' ? changed : `${changed.join('\n')}\n`);
  return path;
}

/** The line index of the first line of a kind (0 is the output). */
function firstOf(lines: readonly string[], kind: 'statement' | 'fact' | 'proposal'): number {
  const index = lines.findIndex((line) => line.startsWith(`{"${kind}":`));
  if (index < 0) throw new Error(`no ${kind} line`);
  return index;
}

let revA: Written;
const all = new Map<string, Written>();

beforeAll(async () => {
  for (const model of MODELS) all.set(model, await written(model, model));
  const found = all.get('demo-hotel-mep-rev-a');
  if (found === undefined) throw new Error('rev A was written');
  revA = found;
}, 300_000);

afterAll(() => {
  rmSync(WORK, { recursive: true, force: true });
});

describe('IFC-1 · R-027 · F-IFC-04 · ADR 0034 (gated: ifc-values; waits for ifc-input 6.2.1, 6.2.2, 6.2.3, 6.2.10): the per-line form reads back to the job\'s own section', { timeout: 120_000 }, () => {
  it.each(MODELS)('IFC-1 · F-IFC-04: %s: the worker\'s line-by-line reading gives the in-memory output, and its section opens to the same facts and proposals', async (model) => {
    const source = all.get(model);
    if (source === undefined) throw new Error(`${model} was written`);
    const gates = openGates();
    const read = await readJobOutput(source.path, source.request, gates);
    if (!read.ok) throw new Error(`refused: ${read.code} ${JSON.stringify(read.problems)}`);
    const inMemory = parseExtractionOutput(parse(JSON.stringify(source.inMemory), { schema: 'json' }) as unknown);
    if (!inMemory.ok) throw new Error('the in-memory output is valid');
    const { ifcValues: streamedSection, ...streamed } = read.output;
    const { ifcValues: inMemorySection, ...rest } = inMemory.value;
    expect(streamed).toEqual(rest);
    const opened = openIfcValues(streamedSection, gates);
    expect(opened.open).toBe(true);
    expect(opened).toEqual(openIfcValues(inMemorySection, gates));
    if (!opened.open) return;
    expect(opened.facts.length).toBeGreaterThan(0);
    expect(read.lines).toBe(readFileSync(source.path, 'utf8').split('\n').length - 1);
  });
});

describe('F-INGEST-04 · R-027 · ADR 0034 (gated: ifc-values): a line refused refuses the whole output, with a named code', { timeout: 120_000 }, () => {
  async function refusal(path: string, limits?: Parameters<typeof readJobOutput>[3]): Promise<{ readonly code: string; readonly problems: readonly string[] }> {
    const read = await readJobOutput(path, revA.request, openGates(), limits);
    if (read.ok) throw new Error('the output was accepted');
    return { code: read.code, problems: read.problems.map((problem) => problem.code) };
  }

  it('F-INGEST-04: a file cut inside a line is output_truncated; cut at a line end, or right after the output, ifc_values_truncated', async () => {
    const text = readFileSync(revA.path, 'utf8');
    expect(await refusal(edited(revA, () => text.slice(0, text.length - 20)))).toMatchObject({ code: 'output_truncated' });
    expect(await refusal(edited(revA, (lines) => lines.slice(0, -1)))).toEqual({ code: 'ifc_values_truncated', problems: ['stream:truncated'] });
    expect(await refusal(edited(revA, (lines) => lines.slice(0, 1)))).toEqual({ code: 'ifc_values_truncated', problems: ['stream:header'] });
    expect(await refusal(edited(revA, (lines) => lines[0] ?? ''))).toEqual({ code: 'ifc_values_truncated', problems: ['stream:header'] });
  });

  it('F-INGEST-04: a line past the bound is output_line_too_long (1 MiB, and any bound the reader is given)', async () => {
    const long = `{"statement":{"stepId":1,"text":"#1=${'X'.repeat(IFC_VALUES_LINE_MAX_BYTES)}"}}`;
    expect(await refusal(edited(revA, (lines) => [lines[0] ?? '', lines[1] ?? '', long, ...lines.slice(2)]))).toMatchObject({ code: 'output_line_too_long' });
    expect(await refusal(revA.path, { outputBytes: 4 * 1024 * 1024, lineBytes: 64, gatedBytes: 512 * 1024 * 1024 })).toMatchObject({ code: 'output_line_too_long' });
  });

  it('F-INGEST-04: a line that is not JSON is output_line_malformed', async () => {
    expect(await refusal(edited(revA, (lines) => lines.map((line, index) => (index === firstOf(lines, 'fact') ? line.slice(0, -3) : line))))).toMatchObject({ code: 'output_line_malformed' });
  });

  it('F-INGEST-04 · IFC-1: a line the contract refuses is ifc_values_invalid, with the problem\'s code and never its text', async () => {
    const withExcerpt = await refusal(edited(revA, (lines) => lines.map((line, index) => (index === firstOf(lines, 'fact') ? line.replace('{"fact":{', '{"fact":{"excerpt":"TEST",') : line))));
    expect(withExcerpt).toEqual({ code: 'ifc_values_invalid', problems: ['unknown_key'] });
    const unknownStatement = await refusal(edited(revA, (lines) => lines.map((line, index) => (index === firstOf(lines, 'fact') ? line.replace(/"stepIds":\[[0-9]+\]/u, '"stepIds":[999999999]') : line))));
    expect(unknownStatement).toEqual({ code: 'ifc_values_invalid', problems: ['stream:unknown_statement'] });
    const notItsOwn = await refusal(edited(revA, (lines) => lines.map((line, index) => (index === firstOf(lines, 'statement') ? line.replace(/"text":"#[0-9]+=/u, '"text":"#7=') : line))));
    expect(notItsOwn).toEqual({ code: 'ifc_values_invalid', problems: ['stream:statement'] });
    const unknownFact = await refusal(edited(revA, (lines) => lines.map((line, index) => (index === firstOf(lines, 'proposal') ? line.replace(/"evidenceFactIds":\["[^"]+"/u, '"evidenceFactIds":["f-not-written"') : line))));
    expect(unknownFact.code).toBe('ifc_values_invalid');
    expect(unknownFact.problems).toContain('invariant:ifc_proposals');
  });

  it('F-INGEST-04: lines out of order, a statement no fact quotes, a line too many, or a section where the output may carry none are refused', async () => {
    const order = await refusal(
      edited(revA, (lines) => {
        const fact = firstOf(lines, 'fact');
        const moved = [...lines];
        const [line] = moved.splice(fact, 1);
        moved.splice(fact - 1, 0, line ?? '');
        return moved;
      }),
    );
    expect(order).toEqual({ code: 'ifc_values_invalid', problems: ['stream:order'] });
    const unquoted = await refusal(
      edited(revA, (lines) => {
        const header = parse(lines[1] ?? '', { schema: 'json' }) as { ifcValuesStream: { statements: number } };
        header.ifcValuesStream.statements += 1;
        const fact = firstOf(lines, 'fact');
        return [lines[0] ?? '', JSON.stringify(header), ...lines.slice(2, fact), '{"statement":{"stepId":999999998,"text":"#999999998=IFCTEST();"}}', ...lines.slice(fact)];
      }),
    );
    expect(unquoted).toEqual({ code: 'ifc_values_invalid', problems: ['stream:unquoted_statement'] });
    expect(await refusal(edited(revA, (lines) => [...lines, lines.at(-1) ?? '']))).toEqual({ code: 'ifc_values_excess', problems: ['stream:excess'] });
    const absent = await refusal(edited(revA, (lines) => [lines[0] ?? '', (lines[1] ?? '').replace('"present"', '"absent"'), ...lines.slice(2)]));
    expect(absent).toEqual({ code: 'ifc_values_invalid', problems: ['stream:section'] });
    const noRecord = await refusal(
      edited(revA, (lines) => {
        const output = parse(lines[0] ?? '', { schema: 'json' }) as Record<string, unknown>;
        delete output['ifcModel'];
        return [JSON.stringify(output), ...lines.slice(1)];
      }),
    );
    expect(noRecord).toEqual({ code: 'ifc_values_invalid', problems: ['invariant:format_sections'] });
  });
});

/** The reader's command line in a process of its own, as in its sandbox (its image gives V8 a 2 GB heap), timed; its output kept at `keep`. */
class ReaderProcessRunner implements ExtractorRunner {
  readonly runs: { readonly status: number | null; readonly seconds: number; readonly maxRssKb?: number }[] = [];
  private readonly script = join(WORK, 'reader-child.mts');

  constructor(private readonly keep?: string) {
    writeFileSync(
      this.script,
      [
        'const [cli, ...args] = process.argv.slice(2);',
        'const { main } = await import(cli);',
        'const status = await main(args, () => undefined);',
        'process.stdout.write(JSON.stringify({ status, maxRssKb: process.resourceUsage().maxRSS }));',
        'process.exitCode = status;',
      ].join('\n'),
    );
  }

  run(job: SandboxJob): Promise<SandboxOutcome> {
    if (job.reader !== 'ifc-reader') return Promise.resolve({ outcome: 'failed', code: 'extractor_failed' });
    const started = Date.now();
    const args = ['--request', job.requestPath, '--document', job.inputPath, '--out', job.outputDirectory, ...(job.idsPath === undefined ? [] : ['--ids', job.idsPath])];
    const child = spawn(process.execPath, ['--max-old-space-size=2048', '--import', 'tsx', this.script, join(REPO_ROOT, 'packages/ifc-reader/src/cli.ts'), ...args], { cwd: REPO_ROOT, stdio: ['ignore', 'pipe', 'ignore'] });
    const chunks: Buffer[] = [];
    child.stdout.on('data', (chunk: Buffer) => chunks.push(chunk));
    return new Promise((resolve) => {
      child.on('exit', (status) => {
        const report = (() => {
          try {
            return parse(Buffer.concat(chunks).toString('utf8'), { schema: 'json' }) as { maxRssKb?: number };
          } catch {
            return {};
          }
        })();
        this.runs.push({ status, seconds: (Date.now() - started) / 1000, ...(report.maxRssKb === undefined ? {} : { maxRssKb: report.maxRssKb }) });
        if (status === 0 && this.keep !== undefined) {
          // The worker removes its folder after the step: a link (or a copy) keeps the file for a measurement of the reading alone.
          try {
            linkSync(join(job.outputDirectory, 'output.json'), this.keep);
          } catch {
            copyFileSync(join(job.outputDirectory, 'output.json'), this.keep);
          }
        }
        resolve(status === 0 ? { outcome: 'finished' } : { outcome: 'failed', code: 'extractor_failed' });
      });
    });
  }
}

/** A runner that writes a fixed file as the job's output (a tampered copy of a real one). */
class FileRunner implements ExtractorRunner {
  constructor(private readonly path: string) {}
  run(job: SandboxJob): Promise<SandboxOutcome> {
    mkdirSync(job.outputDirectory, { recursive: true });
    writeFileSync(join(job.outputDirectory, 'output.json'), readFileSync(this.path));
    return Promise.resolve({ outcome: 'finished' });
  }
}

describe('F-INGEST-04 · F-IFC-03 · ADR 0034 (gated: ifc-values; waits for ifc-input 6.2.1, 6.2.2, 6.2.3, 6.2.10): through the worker', () => {
  let api: TestApi;
  const perfHash = existsSync(PERF) ? contentHashOf(readFileSync(PERF)) : undefined;

  beforeAll(async () => {
    const fixtures = fixtureUploadGuard(REPO_ROOT);
    // The perf model is the perf profile's output, never in the manifest: this suite's guard takes its hash too.
    api = await startTestApi({ readModels: true, uploadGuard: { accepts: (hash) => fixtures.accepts(hash) || hash === perfHash } });
  }, 300_000);

  afterAll(async () => {
    await api.stop();
  });

  function worker(runner: ExtractorRunner): AnalysisWorker {
    return new AnalysisWorker({ store: api.services.store, files: api.files, log: api.services.log }, runner, {
      workerId: 'test-stream-worker',
      serviceId: api.extractionAccountId,
      gates: openGates(),
      ...(api.services.modelReading === undefined ? {} : { modelReading: api.services.modelReading }),
      maxAttempts: 1,
      retryAfterSeconds: 0,
      staleAfterSeconds: 3600,
    });
  }

  async function uploaded(label: string, fileName: string, bytes: Buffer): Promise<{ readonly projectId: string; readonly documentId: string }> {
    const { ownerId, projectId } = await ownerWithProject(api, label);
    const auth = await signIn(api, ownerId);
    const result = await upload(api, auth, projectId, fileName, bytes, 8 * 1024 * 1024);
    const documentId = result.body.documentId;
    if (documentId === undefined) throw new Error(`the upload answered ${String(result.status)} ${String(result.body.code)}`);
    return { projectId, documentId };
  }

  it('F-INGEST-04: a malformed line in a model\'s output fails the job with output_line_malformed, and nothing of the output is stored', { timeout: 300_000 }, async () => {
    const { projectId, documentId } = await uploaded('proposed stream, malformed line', 'demo-hotel-mep-rev-a.ifc', readFileSync(join(REPO_ROOT, 'fixtures/ifc/demo-hotel-mep-rev-a.ifc')));
    const bad = edited(revA, (lines) =>
      lines.map((line, index) => {
        if (index === 0) {
          const output = parse(line, { schema: 'json' }) as { job: Record<string, string> };
          output.job['projectId'] = projectId;
          output.job['documentId'] = documentId;
          return JSON.stringify(output);
        }
        return index === firstOf(lines, 'fact') + 3 ? '{"fact": not json' : line;
      }),
    );
    const stored = (): Promise<unknown> =>
      withRequest(api.database.app, { userId: api.extractionAccountId, projectId }, async (request) => ({
        records: await readModelRecords(request, documentId),
        texts: await readDocumentTexts(request, revA.request.job.contentHash, ''),
        elements: await readIfcElements(request, documentId),
      }));
    const before = await stored();
    // Before the job: only what the upload registered (the file's name), no model record, no IFC text, no element.
    expect(before).toMatchObject({ records: [], elements: [] });
    const steps = await worker(new FileRunner(bad)).drain();
    expect(steps.map((step) => (step.kind === 'failed' || step.kind === 'retry' ? step.code : step.kind))).toEqual(['output_line_malformed']);
    expect(await stored()).toEqual(before);
  });

  it.runIf(perfHash !== undefined)('F-INGEST-04 · F-IFC-03: the perf model, refused as output.too_large before, runs through the reader, the worker\'s line-by-line reading and the gated value path', { timeout: 1_800_000 }, async () => {
    const bytes = readFileSync(PERF);
    const uploadStarted = Date.now();
    const { projectId, documentId } = await uploaded('proposed stream, perf model', 'demo-hotel-perf.ifc', bytes);
    const uploadSeconds = (Date.now() - uploadStarted) / 1000;
    const kept = join(WORK, 'perf-output.json');
    const runner = new ReaderProcessRunner(kept);
    const started = Date.now();
    const steps = await worker(runner).drain();
    const stepSeconds = (Date.now() - started) / 1000;
    expect(steps.map((step) => step.kind)).toEqual(['done']);
    expect(runner.runs).toHaveLength(1);
    const counts = await withRequest(api.database.app, { userId: api.extractionAccountId, projectId }, async (request) => {
      const elements = await readIfcElements(request, documentId);
      const kinds = ['building', 'storey', 'space', 'zone', 'element'] as const;
      return {
        records: (await readModelRecords(request, documentId)).length,
        statements: (await readDocumentTexts(request, contentHashOf(bytes), 'ifc:step:')).length,
        byKind: Object.fromEntries(kinds.map((kind) => [kind, elements.filter((element) => element.kind === kind).length])),
      };
    });
    // The quoted statements are stored as the model's text; the building, its 186 storeys and 22,264 spaces are registered.
    expect(counts.records).toBe(1);
    expect(counts.statements).toBeGreaterThan(200_000);
    expect(counts.byKind).toMatchObject({ building: 1, storey: 186, space: 22_264 });
    // The worker's reading alone, on the same file: line by line, into the sealed section.
    const rssBefore = process.memoryUsage().rss;
    const readStarted = Date.now();
    const read = await readJobOutput(kept, { contractVersion: '1.0.0', job: { projectId, documentId, contentHash: contentHashOf(bytes) }, declaredFormat: 'ifc', ifcValues: true, datasets: [], derivatives: [], limits: EXTRACTION_LIMITS }, openGates());
    const readSeconds = (Date.now() - readStarted) / 1000;
    const rssAfterRead = process.memoryUsage().rss;
    expect(read).toMatchObject({ ok: true });
    const reader = runner.runs[0];
    const report = {
      model: { bytes: bytes.length },
      uploadSeconds,
      readerProcess: { seconds: reader?.seconds, peakRssMB: reader?.maxRssKb === undefined ? undefined : Math.round((reader.maxRssKb * 1024) / 1e6) },
      workerStepSeconds: stepSeconds,
      workerStepWithoutReaderSeconds: reader === undefined ? undefined : Math.round((stepSeconds - reader.seconds) * 10) / 10,
      readingAlone: { seconds: readSeconds, lines: read.ok ? read.lines : undefined, bytes: read.bytesRead, rssGrowthMB: Math.round((rssAfterRead - rssBefore) / 1e6) },
      thisProcessPeakRssMB: Math.round((process.resourceUsage().maxRSS * 1024) / 1e6),
      stored: counts,
    };
    process.stdout.write(`ADR 0034 perf measurement: ${JSON.stringify(report)}\n`);
  });
});
