"""Generated by packages/extraction-contract/src/generator: do not edit.

Source: packages/extraction-contract/src/extraction-contract.schema.json. Change the schema and
run `pnpm --filter @sovitech/extraction-contract generate`; a drift test fails when this file,
schema.json and the source disagree. The types are here; every constraint is in schema.json,
which _validate.py reads, so the Python side and the zod side check the same rules.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

CONTRACT_VERSION = "1.0.0"
ENTRY_POINTS = ("ExtractionOutput", "ExtractionRequest", "EvidenceLocator")
INVARIANT_IDS = (
    "box_ordered",
    "request_consistent",
    "format_sections",
    "status_matches_format",
    "page_coverage",
    "text_blocks",
    "sheet_coverage",
    "hidden_reported",
    "finding_locators",
    "ifc_model_record",
    "ifc_value_locators",
    "ifc_proposals",
    "derivatives_keyed",
    "read_below_total",
)

type Uuid = str
type ContentHash = str
type Code = str
type VersionText = str
type Format = Literal["pdf", "xlsx", "ifc", "rvt", "dwg", "docx", "jpg", "png", "zip", "other"]
type PageNumber = int
type Coordinate = float
type Box = tuple[Coordinate, Coordinate, Coordinate, Coordinate]
type SheetName = str
type CellRef = str
type RangeRef = str
type AnchorId = str
type GlobalId = str
type StepId = int
type IfcSchemaId = str
type IfcClassName = str
type IfcTypeName = str
type FactId = str
type ProposalId = str
type FieldKey = str
type IfcGateId = Literal[
    "ifc-values",
    "ifc-code-inference",
    "ifc-identity",
    "ifc-untagged-count",
    "ifc-areas",
    "ifc-geometry",
    "ifc-units",
    "ifc-hidden-content",
    "dataset-asset-taxonomy",
    "dataset-glossary",
]
type DerivativeKind = Literal["fragments", "glb", "svg_plan", "thumbnail", "page_image"]
type PartlyAnalysedStatusUnit = Literal["pages", "sheets"]
type StoredOnlyStatusFormatWord = Literal[
    "IFC model",
    "RVT model",
    "DWG drawing",
    "DOCX file",
    "JPG image",
    "PNG image",
    "ZIP archive",
    "PDF scan",
]
type AnalysisFailedStatusReason = Literal[
    "unreadable_file",
    "encrypted",
    "unrecognised_format",
    "format_mismatch",
    "time_limit",
    "memory_limit",
    "internal_error",
]
type AnalysisStatus = (
    AnalysedStatus | PartlyAnalysedStatus | StoredOnlyStatus | AnalysisFailedStatus
)
type UnreadPageRangeReason = Literal[
    "no_text_layer",
    "render_error",
    "page_limit",
    "time_limit",
    "truncated",
]
type SheetCoverageStatus = Literal["read", "not_read"]
type SheetCoverageReason = Literal["chart_sheet", "unsupported_sheet", "cell_limit", "read_error"]
type IfcUnreadScope = Literal["header", "class", "element", "property_set", "geometry"]
type PdfHiddenReason = Literal[
    "invisible_render_mode",
    "fill_matches_background",
    "tiny_text",
    "outside_page",
    "hidden_layer",
    "clipped",
]
type PdfPageRotation = Literal[0, 90, 180, 270]
type XlsxHiddenReason = Literal[
    "hidden_sheet",
    "very_hidden_sheet",
    "hidden_row",
    "hidden_column",
    "font_matches_fill",
]
type XlsxCellValueType = Literal[
    "number",
    "shared_string",
    "inline_string",
    "formula_string",
    "boolean",
    "error",
    "date",
]
type XlsxSheetVisibility = Literal["visible", "hidden", "very_hidden"]
type SchemaCheckOutcome = Literal["no_problems", "problems", "not_run"]
type IdsSpecResultOutcome = Literal["pass", "fail", "not_applicable"]
type IfcModelRecordProcessing = Literal["complete", "partial", "failed"]
type IfcPathThrough = Literal["occurrence", "type_object"]
type IfcRelationPathRelation = Literal[
    "contained_in_spatial_structure",
    "aggregates",
    "assigns_to_group",
    "defines_by_type",
    "services_buildings",
    "referenced_in_spatial_structure",
    "flow_control_elements",
    "nests",
    "connects_ports",
    "associates_classification",
]
type IfcPath = IfcAttributePath | IfcPropertyPath | IfcQuantityPath | IfcRelationPath
type StepBooleanToken = Literal[".T.", ".F."]
type StepLogicalToken = Literal[".T.", ".F.", ".U."]
type StepScalar = (
    StepReal
    | StepInteger
    | StepString
    | StepBoolean
    | StepLogical
    | StepEnumeration
    | StepBinary
    | StepReference
)
type StepValue = (
    StepReal
    | StepInteger
    | StepString
    | StepBoolean
    | StepLogical
    | StepEnumeration
    | StepBinary
    | StepReference
    | StepUnset
    | StepDerived
    | StepList
)
type DeclaredUnitSource = Literal["project_unit_assignment", "value_unit"]
type DeclaredUnitUnitKind = Literal[
    "si",
    "conversion_based",
    "derived",
    "monetary",
    "context_dependent",
]
type ProposalSubjectKind = Literal[
    "project",
    "building",
    "level",
    "zone",
    "asset",
    "metering_point",
]
type IfcProposalMechanism = Literal[
    "direct_read",
    "relation",
    "tag_source",
    "class_mapping",
    "name_term",
    "quantity_set_area",
    "geometry",
]
type ProposalValue = FactProposalValue | ChoiceProposalValue
type IfcCandidateProposalSourceClaim = Literal["document", "ai_inference", "calculated"]
type IfcCandidateProposalConfidence = Literal["high", "medium", "low"]
type FindingLocator = (
    PdfFindingLocator | XlsxFindingLocator | IfcFindingLocator | FileFindingLocator
)
type FindingKind = Literal["embedded_instruction", "hidden_text", "schema_error", "hidden_content"]
type DerivativeMediaType = Literal[
    "application/octet-stream",
    "model/gltf-binary",
    "image/svg+xml",
    "image/png",
    "image/webp",
]
type EvidenceLocator = PdfEvidenceLocator | XlsxEvidenceLocator


@dataclass(frozen=True, slots=True)
class ToolVersion:
    """#/$defs/ToolVersion"""

    name: str
    version: VersionText


@dataclass(frozen=True, slots=True)
class DatasetRef:
    """#/$defs/DatasetRef"""

    id: str
    version: VersionText


@dataclass(frozen=True, slots=True)
class Job:
    """#/$defs/Job"""

    project_id: Uuid
    document_id: Uuid
    content_hash: ContentHash


@dataclass(frozen=True, slots=True)
class IdsRef:
    """#/$defs/IdsRef"""

    id: str
    version: VersionText
    draft: bool
    sha256: ContentHash


@dataclass(frozen=True, slots=True)
class Limits:
    """#/$defs/Limits"""

    max_pages: int
    max_cells_per_sheet: int
    wall_clock_seconds: int


@dataclass(frozen=True, slots=True)
class ExtractionRequest:
    """#/$defs/ExtractionRequest"""

    contract_version: Literal["1.0.0"]
    job: Job
    declared_format: Format
    ifc_values: bool
    datasets: tuple[DatasetRef, ...]
    derivatives: tuple[DerivativeKind, ...]
    limits: Limits
    ids: IdsRef | None = None


@dataclass(frozen=True, slots=True)
class Producer:
    """#/$defs/Producer"""

    name: Literal["sovitech-extractor"]
    version: VersionText
    libraries: tuple[ToolVersion, ...]


@dataclass(frozen=True, slots=True)
class AnalysedStatus:
    """#/$defs/AnalysedStatus"""

    status: Literal["analysed"]


@dataclass(frozen=True, slots=True)
class PartlyAnalysedStatus:
    """#/$defs/PartlyAnalysedStatus"""

    status: Literal["partly_analysed"]
    unit: PartlyAnalysedStatusUnit
    read: int
    total: int


@dataclass(frozen=True, slots=True)
class StoredOnlyStatus:
    """#/$defs/StoredOnlyStatus"""

    status: Literal["stored_only"]
    format_word: StoredOnlyStatusFormatWord


@dataclass(frozen=True, slots=True)
class AnalysisFailedStatus:
    """#/$defs/AnalysisFailedStatus"""

    status: Literal["failed"]
    reason: AnalysisFailedStatusReason


@dataclass(frozen=True, slots=True)
class PageRange:
    """#/$defs/PageRange"""

    first: PageNumber
    last: PageNumber


@dataclass(frozen=True, slots=True)
class UnreadPageRange:
    """#/$defs/UnreadPageRange"""

    first: PageNumber
    last: PageNumber
    reason: UnreadPageRangeReason


@dataclass(frozen=True, slots=True)
class PageCoverage:
    """#/$defs/PageCoverage"""

    total: PageNumber
    read: tuple[PageRange, ...]
    unread: tuple[UnreadPageRange, ...]


@dataclass(frozen=True, slots=True)
class SheetCoverage:
    """#/$defs/SheetCoverage"""

    sheet: SheetName
    status: SheetCoverageStatus
    reason: SheetCoverageReason | None = None


@dataclass(frozen=True, slots=True)
class IfcUnread:
    """#/$defs/IfcUnread"""

    scope: IfcUnreadScope
    reason: Code
    global_ids: tuple[GlobalId, ...]
    step_ids: tuple[StepId, ...]
    ifc_class: IfcClassName | None = None


@dataclass(frozen=True, slots=True)
class IfcCoverage:
    """#/$defs/IfcCoverage"""

    classes_read: tuple[IfcClassName, ...]
    not_read: tuple[IfcUnread, ...]


@dataclass(frozen=True, slots=True)
class Coverage:
    """#/$defs/Coverage"""

    pages: PageCoverage | None = None
    sheets: tuple[SheetCoverage, ...] | None = None
    ifc: IfcCoverage | None = None


@dataclass(frozen=True, slots=True)
class CharBox:
    """#/$defs/CharBox"""

    start: int
    end: int
    box: Box


@dataclass(frozen=True, slots=True)
class TextBlock:
    """#/$defs/TextBlock"""

    anchor_id: AnchorId
    text: str
    bbox: Box
    char_boxes: tuple[CharBox, ...]
    hidden: tuple[PdfHiddenReason, ...]
    layer: str | None = None


@dataclass(frozen=True, slots=True)
class PdfPage:
    """#/$defs/PdfPage"""

    page: PageNumber
    media_box: Box
    rotation: PdfPageRotation
    blocks: tuple[TextBlock, ...]


@dataclass(frozen=True, slots=True)
class PdfContent:
    """#/$defs/PdfContent"""

    pages: tuple[PdfPage, ...]


@dataclass(frozen=True, slots=True)
class XlsxCell:
    """#/$defs/XlsxCell"""

    ref: CellRef
    value_type: XlsxCellValueType
    raw: str
    number_format: str
    hidden: tuple[XlsxHiddenReason, ...]
    formula: str | None = None


@dataclass(frozen=True, slots=True)
class XlsxSheet:
    """#/$defs/XlsxSheet"""

    name: SheetName
    visibility: XlsxSheetVisibility
    cells: tuple[XlsxCell, ...]
    merged_ranges: tuple[RangeRef, ...]


@dataclass(frozen=True, slots=True)
class XlsxContent:
    """#/$defs/XlsxContent"""

    sheets: tuple[XlsxSheet, ...]


@dataclass(frozen=True, slots=True)
class IfcHeader:
    """#/$defs/IfcHeader"""

    schema: IfcSchemaId
    authoring_tool: str | None = None
    ifc_project_global_id: GlobalId | None = None


@dataclass(frozen=True, slots=True)
class SchemaCheck:
    """#/$defs/SchemaCheck"""

    tool: ToolVersion
    outcome: SchemaCheckOutcome


@dataclass(frozen=True, slots=True)
class IdsSpecResult:
    """#/$defs/IdsSpecResult"""

    spec_id: str
    outcome: IdsSpecResultOutcome
    applicable: int
    passed: int
    failed: int
    failing_global_ids: tuple[GlobalId, ...]


@dataclass(frozen=True, slots=True)
class IdsResults:
    """#/$defs/IdsResults"""

    ids: IdsRef
    tool: ToolVersion
    specifications: tuple[IdsSpecResult, ...]


@dataclass(frozen=True, slots=True)
class IfcModelRecord:
    """#/$defs/IfcModelRecord"""

    header: IfcHeader
    classes_present: tuple[IfcClassName, ...]
    processing: IfcModelRecordProcessing
    schema_check: SchemaCheck
    ids: IdsResults | None = None


@dataclass(frozen=True, slots=True)
class IfcAttributePath:
    """#/$defs/IfcAttributePath"""

    kind: Literal["attribute"]
    through: IfcPathThrough
    attribute: str


@dataclass(frozen=True, slots=True)
class IfcPropertyPath:
    """#/$defs/IfcPropertyPath"""

    kind: Literal["property"]
    through: IfcPathThrough
    property_set: str
    property: str


@dataclass(frozen=True, slots=True)
class IfcQuantityPath:
    """#/$defs/IfcQuantityPath"""

    kind: Literal["quantity"]
    through: IfcPathThrough
    quantity_set: str
    quantity: str


@dataclass(frozen=True, slots=True)
class IfcRelationPath:
    """#/$defs/IfcRelationPath"""

    kind: Literal["relation"]
    relation: IfcRelationPathRelation
    related_global_id: GlobalId


@dataclass(frozen=True, slots=True)
class IfcLocator:
    """#/$defs/IfcLocator"""

    content_hash: ContentHash
    schema: IfcSchemaId
    global_id: GlobalId
    step_ids: tuple[StepId, ...]
    path: IfcPath


@dataclass(frozen=True, slots=True)
class StepReal:
    """#/$defs/StepReal"""

    kind: Literal["real"]
    token: str
    ifc_type: IfcTypeName | None = None


@dataclass(frozen=True, slots=True)
class StepInteger:
    """#/$defs/StepInteger"""

    kind: Literal["integer"]
    token: str
    ifc_type: IfcTypeName | None = None


@dataclass(frozen=True, slots=True)
class StepString:
    """#/$defs/StepString"""

    kind: Literal["string"]
    token: str
    text: str
    ifc_type: IfcTypeName | None = None


@dataclass(frozen=True, slots=True)
class StepBoolean:
    """#/$defs/StepBoolean"""

    kind: Literal["boolean"]
    token: StepBooleanToken
    ifc_type: IfcTypeName | None = None


@dataclass(frozen=True, slots=True)
class StepLogical:
    """#/$defs/StepLogical"""

    kind: Literal["logical"]
    token: StepLogicalToken
    ifc_type: IfcTypeName | None = None


@dataclass(frozen=True, slots=True)
class StepEnumeration:
    """#/$defs/StepEnumeration"""

    kind: Literal["enumeration"]
    token: str
    ifc_type: IfcTypeName | None = None


@dataclass(frozen=True, slots=True)
class StepBinary:
    """#/$defs/StepBinary"""

    kind: Literal["binary"]
    token: str
    ifc_type: IfcTypeName | None = None


@dataclass(frozen=True, slots=True)
class StepReference:
    """#/$defs/StepReference"""

    kind: Literal["reference"]
    step_id: StepId


@dataclass(frozen=True, slots=True)
class StepUnset:
    """#/$defs/StepUnset"""

    kind: Literal["unset"]


@dataclass(frozen=True, slots=True)
class StepDerived:
    """#/$defs/StepDerived"""

    kind: Literal["derived"]


@dataclass(frozen=True, slots=True)
class StepList:
    """#/$defs/StepList"""

    kind: Literal["list"]
    items: tuple[StepScalar, ...]
    ifc_type: IfcTypeName | None = None


@dataclass(frozen=True, slots=True)
class DeclaredUnit:
    """#/$defs/DeclaredUnit"""

    source: DeclaredUnitSource
    step_id: StepId
    unit_kind: DeclaredUnitUnitKind
    unit_type: str
    name: str
    prefix: str | None = None


@dataclass(frozen=True, slots=True)
class IfcFact:
    """#/$defs/IfcFact"""

    id: FactId
    locator: IfcLocator
    value: StepValue
    excerpt: str
    declared_unit: DeclaredUnit | None = None


@dataclass(frozen=True, slots=True)
class ProposalSubject:
    """#/$defs/ProposalSubject"""

    kind: ProposalSubjectKind
    element_global_id: GlobalId


@dataclass(frozen=True, slots=True)
class FactProposalValue:
    """#/$defs/FactProposalValue"""

    kind: Literal["fact"]
    fact_id: FactId


@dataclass(frozen=True, slots=True)
class ChoiceProposalValue:
    """#/$defs/ChoiceProposalValue"""

    kind: Literal["choice"]
    choice: str


@dataclass(frozen=True, slots=True)
class IfcCandidateProposal:
    """#/$defs/IfcCandidateProposal"""

    id: ProposalId
    subject: ProposalSubject
    field_key: FieldKey
    source_claim: IfcCandidateProposalSourceClaim
    mechanism: IfcProposalMechanism
    requires_gates: tuple[IfcGateId, ...]
    datasets: tuple[DatasetRef, ...]
    value: ProposalValue
    evidence_fact_ids: tuple[FactId, ...]
    confidence: IfcCandidateProposalConfidence | None = None


@dataclass(frozen=True, slots=True)
class IfcValues:
    """#/$defs/IfcValues"""

    facts: tuple[IfcFact, ...]
    candidate_proposals: tuple[IfcCandidateProposal, ...]


@dataclass(frozen=True, slots=True)
class PdfFindingLocator:
    """#/$defs/PdfFindingLocator"""

    kind: Literal["pdf"]
    page: PageNumber
    anchor_id: AnchorId | None = None
    bbox: Box | None = None


@dataclass(frozen=True, slots=True)
class XlsxFindingLocator:
    """#/$defs/XlsxFindingLocator"""

    kind: Literal["xlsx"]
    sheet: SheetName
    cell: CellRef | None = None


@dataclass(frozen=True, slots=True)
class IfcFindingLocator:
    """#/$defs/IfcFindingLocator"""

    kind: Literal["ifc"]
    step_ids: tuple[StepId, ...]
    global_id: GlobalId | None = None
    ifc_class: IfcClassName | None = None


@dataclass(frozen=True, slots=True)
class FileFindingLocator:
    """#/$defs/FileFindingLocator"""

    kind: Literal["file"]


@dataclass(frozen=True, slots=True)
class Finding:
    """#/$defs/Finding"""

    kind: FindingKind
    code: Code
    locator: FindingLocator


@dataclass(frozen=True, slots=True)
class Derivative:
    """#/$defs/Derivative"""

    kind: DerivativeKind
    project_id: Uuid
    content_hash: ContentHash
    relative_path: str
    sha256: ContentHash
    media_type: DerivativeMediaType
    producer: ToolVersion
    storey_global_id: GlobalId | None = None
    page: PageNumber | None = None


@dataclass(frozen=True, slots=True)
class ExtractionOutput:
    """#/$defs/ExtractionOutput"""

    contract_version: Literal["1.0.0"]
    producer: Producer
    job: Job
    format: Format
    analysis: AnalysisStatus
    coverage: Coverage
    findings: tuple[Finding, ...]
    derivatives: tuple[Derivative, ...]
    pdf: PdfContent | None = None
    xlsx: XlsxContent | None = None
    ifc_model: IfcModelRecord | None = None
    ifc_values: IfcValues | None = None


@dataclass(frozen=True, slots=True)
class PdfEvidenceLocator:
    """#/$defs/PdfEvidenceLocator"""

    page: PageNumber
    bbox: Box | None = None


@dataclass(frozen=True, slots=True)
class XlsxEvidenceLocator:
    """#/$defs/XlsxEvidenceLocator"""

    sheet: SheetName
    cell: CellRef | None = None
